//===- AArch64_AutoRoundTripTests.cpp - Auto-generated roundtrip tests --*- C++ -*-===//
//
// NeverD Decompiler
//
//===----------------------------------------------------------------------===//
//
// AUTO-GENERATED by scripts/gen_roundtrip_tests.py
// 54 instructions mapped out of 1426 total aarch64 capstone IDs.
//
//===----------------------------------------------------------------------===//

#include "SemanticRoundTripFixture.h"

TEST_P(AArch64RoundTrip, AutoLiftVerify) {
  roundTripAArch64(GetParam());
}

// clang-format off

static const std::vector<RoundTripTC> kAutoAArch64RoundTrip = {
  {"adc",
   "long rt_adc(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"adds xzr, xzr, xzr\\n\\tadc %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {50, 30}, "AutoRT"},

  {"adcs",
   "long rt_adcs(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"adds xzr, xzr, xzr\\n\\tadcs %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {50, 30}, "AutoRT"},

  {"add",
   "long rt_add(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"add %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {50, 30}, "AutoRT"},

  {"adds",
   "long rt_adds(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"adds %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {100, 50}, "AutoRT"},

  {"and",
   "long rt_and(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"and %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {65280, 4080}, "AutoRT"},

  {"ands",
   "long rt_ands(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"ands %w0, %w1, %w2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {65280, 4080}, "AutoRT"},

  {"asr",
   "long rt_asr(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"asr %0, %1, #2\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {0xFFFFFFFFFFFFFF00ULL}, "AutoRT"},

  {"bfm",
   "long rt_bfm(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"bfm %0, %1, #8, #15\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {4294901760}, "AutoRT"},

  {"bic",
   "long rt_bic(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"bic %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {65535, 255}, "AutoRT"},

  {"bics",
   "long rt_bics(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"bics %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {65535, 255}, "AutoRT"},

  {"cls",
   "long rt_cls(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"cls %0, %1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {255}, "AutoRT"},

  {"clz",
   "long rt_clz(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"clz %0, %1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {256}, "AutoRT"},

  {"csel",
   "long rt_csel(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"cmp %1, %2\\n\\tcsel %0, %1, %2, gt\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {100, 50}, "AutoRT"},

  {"csinc",
   "long rt_csinc(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"cmp %1, %2\\n\\tcsinc %0, %1, %2, gt\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {100, 50}, "AutoRT"},

  {"csinv",
   "long rt_csinv(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"cmp %1, %2\\n\\tcsinv %0, %1, %2, gt\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {100, 50}, "AutoRT"},

  {"csneg",
   "long rt_csneg(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"cmp %1, %2\\n\\tcsneg %0, %1, %2, gt\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {100, 50}, "AutoRT"},

  {"eon",
   "long rt_eon(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"eon %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {255, 85}, "AutoRT"},

  {"eor",
   "long rt_eor(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"eor %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {255, 85}, "AutoRT"},

  {"extr",
   "long rt_extr(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"extr %0, %1, %2, #16\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {2863267840, 48059}, "AutoRT"},

  {"lsl",
   "long rt_lsl(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"lsl %0, %1, #4\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {1}, "AutoRT"},

  {"lsr",
   "long rt_lsr(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"lsr %0, %1, #2\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {100}, "AutoRT"},

  {"madd",
   "long rt_madd(long a, long b, long c) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"madd %0, %1, %2, %3\" : \"=r\"(r) : \"r\"(a), \"r\"(b), \"r\"(c));\n"
   "  return r;\n"
   "}\n"
   "",
   {6, 7, 10}, "AutoRT"},

  {"mov",
   "long rt_mov(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"mov %0, %1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {42}, "AutoRT"},

  {"movk",
   "long rt_movk(void) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"movz %0, #0x1234\\n\\tmovk %0, #0x5678, lsl #16\" : \"=r\"(r));\n"
   "  return r;\n"
   "}\n"
   "",
   {}, "AutoRT"},

  {"movn",
   "long rt_movn(void) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"movn %0, #0\" : \"=r\"(r));\n"
   "  return r;\n"
   "}\n"
   "",
   {}, "AutoRT"},

  {"movz",
   "long rt_movz(void) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"movz %0, #0x1234\" : \"=r\"(r));\n"
   "  return r;\n"
   "}\n"
   "",
   {}, "AutoRT"},

  {"msub",
   "long rt_msub(long a, long b, long c) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"msub %0, %1, %2, %3\" : \"=r\"(r) : \"r\"(a), \"r\"(b), \"r\"(c));\n"
   "  return r;\n"
   "}\n"
   "",
   {6, 7, 100}, "AutoRT"},

  {"mul",
   "long rt_mul(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"mul %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {6, 7}, "AutoRT"},

  {"neg",
   "long rt_neg(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"neg %0, %1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {42}, "AutoRT"},

  {"orn",
   "long rt_orn(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"orn %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {240, 15}, "AutoRT"},

  {"orr",
   "long rt_orr(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"orr %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {240, 15}, "AutoRT"},

  {"rbit",
   "long rt_rbit(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"rbit %0, %1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {1}, "AutoRT"},

  {"rev",
   "long rt_rev(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"rev %0, %1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {0x102030405060708ULL}, "AutoRT"},

  {"rev16",
   "long rt_rev16(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"rev16 %0, %1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {0x102030405060708ULL}, "AutoRT"},

  {"rev32",
   "long rt_rev32(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"rev32 %0, %1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {0x102030405060708ULL}, "AutoRT"},

  {"ror",
   "long rt_ror(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"ror %0, %1, #4\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {240}, "AutoRT"},

  {"sbfm",
   "long rt_sbfm(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"sbfm %0, %1, #4, #11\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {43981}, "AutoRT"},

  {"sdiv",
   "long rt_sdiv(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"sdiv %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {100, 7}, "AutoRT"},

  {"smaddl",
   "long rt_smaddl(long a, long b, long c) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"smaddl %0, %w1, %w2, %3\" : \"=r\"(r) : \"r\"(a), \"r\"(b), \"r\"(c));\n"
   "  return r;\n"
   "}\n"
   "",
   {6, 7, 10}, "AutoRT"},

  {"smsubl",
   "long rt_smsubl(long a, long b, long c) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"smsubl %0, %w1, %w2, %3\" : \"=r\"(r) : \"r\"(a), \"r\"(b), \"r\"(c));\n"
   "  return r;\n"
   "}\n"
   "",
   {6, 7, 100}, "AutoRT"},

  {"smulh",
   "long rt_smulh(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"smulh %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {0x100000000ULL, 0x100000000ULL}, "AutoRT"},

  {"smull",
   "long rt_smull(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"smull %0, %w1, %w2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {4294967295, 2}, "AutoRT"},

  {"sub",
   "long rt_sub(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"sub %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {100, 30}, "AutoRT"},

  {"subs",
   "long rt_subs(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"subs %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {100, 30}, "AutoRT"},

  {"sxtb",
   "long rt_sxtb(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"sxtb %0, %w1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {128}, "AutoRT"},

  {"sxth",
   "long rt_sxth(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"sxth %0, %w1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {32768}, "AutoRT"},

  {"sxtw",
   "long rt_sxtw(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"sxtw %0, %w1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {4294967295}, "AutoRT"},

  {"ubfm",
   "long rt_ubfm(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"ubfm %0, %1, #4, #11\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {43981}, "AutoRT"},

  {"udiv",
   "long rt_udiv(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"udiv %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {100, 7}, "AutoRT"},

  {"umaddl",
   "long rt_umaddl(long a, long b, long c) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"umaddl %0, %w1, %w2, %3\" : \"=r\"(r) : \"r\"(a), \"r\"(b), \"r\"(c));\n"
   "  return r;\n"
   "}\n"
   "",
   {6, 7, 10}, "AutoRT"},

  {"umulh",
   "long rt_umulh(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"umulh %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {0x100000000ULL, 0x100000000ULL}, "AutoRT"},

  {"umull",
   "long rt_umull(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"umull %0, %w1, %w2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {4294967295, 2}, "AutoRT"},

  {"uxtb",
   "long rt_uxtb(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"uxtb %w0, %w1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {43981}, "AutoRT"},

  {"uxth",
   "long rt_uxth(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"uxth %w0, %w1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {11259375}, "AutoRT"},

};

// clang-format on

INSTANTIATE_TEST_SUITE_P(AutoRT, AArch64RoundTrip,
                         ::testing::ValuesIn(kAutoAArch64RoundTrip), rtTCName);
