//===- PackageIntegrityTests.cpp - Original SRI regressions ------------===//
//
// NeverD Decompiler
//
//===----------------------------------------------------------------------===//
///
/// \file
/// Independent digest vectors, strongest declarations and original byte scope.
///
//===----------------------------------------------------------------------===//

#include "BlobStore.h"
#include "Internal.h"
#include "PackageArchiveFixture.h"
#include "gtest/gtest.h"
#include "packages/SHA512.h"

#include "neverd/web/PackageIntegrity.h"

#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/Base64.h"
#include "llvm/Support/SHA256.h"

#include <cstdlib>

namespace {
using namespace neverd::web;
constexpr std::string_view ABC512 =
    "ddaf35a193617abacc417349ae20413112e6fa4e89a97ea20a9eeee64b55d39a"
    "2192992a274fc1a836ba3c23a3feebbd454d4423643ce80e2a9ac94fa54ca49f";
constexpr std::string_view ABC384 =
    "cb00753f45a35e8bb5a03d699ac65007272c32ab0eded1631a8b605a43ff5bed"
    "8086072ba1e7cc2358baeca134c825a7";
constexpr std::string_view ABC256 =
    "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad";
std::string sri(std::string_view Algorithm, std::string_view Hex) {
  return std::string(Algorithm) + "-" + llvm::encodeBase64(llvm::fromHex(Hex));
}
Artifact artifact(std::string_view Bytes) {
  BlobStore S(Limits::HardInputBytes);
  S.append(Bytes);
  S.seal();
  Artifact A;
  A.Content = S.whole();
  A.BlobHash = A.Content.digest();
  A.ID = identity("integrity-test", {A.BlobHash});
  return A;
}
PackageIntegrityResult verify(const Artifact &A, const std::string &SRI) {
  const auto M = artifact("{\"dist\":{\"integrity\":\"" + SRI + "\"}}");
  return verifyPackageIntegrity(A, registryPackageIntegrity(M));
}

TEST(WebPackageDigest, StandardVectorsAcrossChunkAndPaddingBoundaries) {
  const std::string Long =
      "abcdefghbcdefghicdefghijdefghijkefghijklfghijklmghijklmn"
      "hijklmnoijklmnopjklmnopqklmnopqrlmnopqrsmnopqrstnopqrstu";
  struct Vector {
    std::string Message, SHA384, SHA512;
  };
  // FIPS algorithm examples / RFC 6234 test vectors, not generated by NeverD.
  const Vector Vectors[]{
      {"",
       "38b060a751ac96384cd9327eb1b1e36a21fdb71114be07434c0cc7bf"
       "63f6e1da274edebfe76f65fbd51ad2f14898b95b",
       "cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce"
       "47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e"},
      {"abc", std::string(ABC384), std::string(ABC512)},
      {Long,
       "09330c33f71147e83d192fc782cd1b4753111b173b3b05d22fa08086e3b0f712"
       "fcc7c71a557e2db966c3e9fa91746039",
       "8e959b75dae313da8cf4f72814fc143f8f7779c6eb9f7fa17299aeadb6889018"
       "501d289e4900f7e4331b99dec4b5433ac7d329eeb6dd26545e96e55b874be909"},
      {std::string(1000000, 'a'),
       "9d0e1809716474cb086e834e310a4a1ced149e9c00f248527972cec5704c2a5b0"
       "7b8b3dc38ecc4ebae97ddd87f3d8985",
       "e718483d0ce769644e2e42c7bc15b4638e1f98b13b2044285632a803afa973eb"
       "de0ff244877ea60a4cb0432ce577c31beb009c5c2c49aa2e4eadb217ad8cc09b"}};
  for (const auto &V : Vectors)
    for (const size_t Chunk : {1, 17, 111, 128, 129, 65536})
      for (const bool Short : {false, true}) {
        SHA512 H(Short);
        for (size_t I = 0; I < V.Message.size(); I += Chunk)
          H.update(std::string_view(V.Message).substr(I, Chunk));
        const auto Expected = Short ? V.SHA384 : V.SHA512;
        EXPECT_EQ(llvm::toHex(H.result(), true), Expected);
        EXPECT_EQ(llvm::toHex(H.result(), true), Expected);
        H.update("");
        EXPECT_EQ(llvm::toHex(H.result(), true), Expected);
      }
}

#ifndef _WIN32
TEST(WebPackageIntegrity, StrongestAlgorithmAndAnyEqualStrengthCandidate) {
  const auto A = artifact("abc");
  const auto Good = sri("sha512", ABC512);
  const auto Wrong = sri("sha512", std::string(128, '0'));
  for (const auto &S : {sri("sha256", ABC256), sri("sha384", ABC384), Good,
                        std::string("sha1-qZk+NkcGgWq6PiVxeFDCbJzQ2J0=")})
    EXPECT_EQ(verify(A, S).Status, "match");
  EXPECT_EQ(verify(A, sri("sha256", ABC256) + " " + Wrong).Status, "mismatch");
  EXPECT_EQ(verify(A, Wrong + " " + Good).Status, "match");
  EXPECT_EQ(verify(A, Good + " " + Wrong).Status, "match");
  EXPECT_EQ(verify(A, Good + " " + sri("sha256", ABC256)).Algorithm, "sha512");
  EXPECT_EQ(verify(A, Good + " " + Wrong).CandidateCount, 2);
  EXPECT_EQ(verify(A, "md5-AAAA " + Good).Status, "match");
  EXPECT_EQ(verify(A, Good + " sha512-malformed").Status, "invalid");
}

TEST(WebPackageIntegrity, UnsupportedInvalidMissingAndGitStayDistinct) {
  const auto A = artifact("abc");
  for (const auto &S : {"", " ", "-AAAA", "sha256-", "sha512-AAAA",
                        "sha1-qZk+NkcGgWq6PiVxeFDCbJzQ2J1=",
                        "sha1-qZk+NkcGgWq6PiVxeFDCbJzQ2J0", "sha!1-AAAA"})
    EXPECT_EQ(verify(A, S).Status, "invalid");
  EXPECT_EQ(verify(A, "md5-AAAA").Status, "unsupported_algorithm");
  EXPECT_EQ(verify(A, sri("sha512", ABC512) + "?x").Status,
            "unsupported_sri_options");
  std::string Huge;
  for (unsigned I = 0; I < 257; ++I)
    Huge += sri("sha256", ABC256) + " ";
  EXPECT_EQ(verify(A, Huge).Status, "integrity_declaration_budget_exceeded");
  const auto Empty = registryPackageIntegrity(artifact(R"({"dist":{}})"));
  EXPECT_EQ(verifyPackageIntegrity(A, Empty).Status, "missing_declaration");
  auto Git = Empty;
  Git.Git = true;
  Git.Value = std::string(40, 'a');
  EXPECT_EQ(verifyPackageIntegrity(A, Git).Status,
            "git_commit_declared_unverified");
  Git.Git = false;
  EXPECT_EQ(verifyPackageIntegrity(A, Git).Status, "invalid");
  for (const auto *JSON : {R"({"dist":{"integrity":42}})", R"({"dist":null})",
                           R"({"dist":{"integrity":"x","integrity":"y"}})"})
    EXPECT_THROW(registryPackageIntegrity(artifact(JSON)), Error);
}

TEST(WebPackageIntegrity, DigestIsOverOriginalGzipNotExpandedTarOrMembers) {
  const auto Tar = test::finishTar(test::tarMember("package/a", "abc"));
  const auto Original = artifact(test::storedGzip(Tar));
  llvm::SHA256 H;
  H.update(Tar);
  const auto ExpandedSRI = "sha256-" + llvm::encodeBase64(H.final());
  EXPECT_EQ(verify(Original, ExpandedSRI).Status, "mismatch");
  EXPECT_EQ(verify(Original, sri("sha256", ABC256)).Status, "mismatch");
  const auto R = verify(Original, sri("sha256", Original.BlobHash));
  EXPECT_EQ(R.Status, "match");
  EXPECT_EQ(R.BlobHash, Original.BlobHash);
  EXPECT_EQ(R.Bytes, Original.Content.size());
  auto CorruptIdentity = Original;
  CorruptIdentity.BlobHash = std::string(64, '0');
  EXPECT_THROW(verify(CorruptIdentity, sri("sha256", Original.BlobHash)),
               Error);
}

TEST(WebPackageIntegrity, LockSelectionRetainsItsExactDeclarationAndGitStatus) {
  PackageAnalysis A;
  A.Kind = "npm-lock";
  A.ArtifactID = "lock";
  A.BlobHash = "captured-lock-hash";
  PackageInstance P;
  P.ID = "package";
  P.Integrity = sri("sha512", ABC512);
  P.IntegrityStatus = packageIntegrityDeclarationStatus(*P.Integrity);
  A.Packages.push_back(P);
  const auto D = lockedPackageIntegrity(A, P.ID);
  EXPECT_EQ(D.ArtifactID, A.ArtifactID);
  EXPECT_EQ(D.SelectionID, P.ID);
  EXPECT_EQ(verifyPackageIntegrity(artifact("abc"), D).Status, "match");
  EXPECT_THROW(lockedPackageIntegrity(A, "other"), Error);
  A.Packages[0].Integrity.reset();
  A.Packages[0].IntegrityStatus = "invalid";
  EXPECT_EQ(
      verifyPackageIntegrity(artifact("abc"), lockedPackageIntegrity(A, P.ID))
          .Status,
      "invalid");
  A.Kind = "package-json";
  EXPECT_THROW(lockedPackageIntegrity(A, P.ID), Error);
}

TEST(WebPackageIntegrity, OfficialClaudeCodeTarballsWhenSupplied) {
  const auto *Directory = std::getenv("NEVERD_CLAUDE_CODE_21296_NPM_DIR");
  if (!Directory)
    GTEST_SKIP()
        << "Official pinned npm originals and registry snapshots not supplied";
  struct Expected {
    const char *Name, *SRI, *SHA256;
    uint64_t Bytes;
  };
  const Expected Cases[]{
      {"claude-code-2.1.296",
       "sha512-OX/k/rpcthMqnFKOWcpNcbiLsMKtAjLOpQNJHlYiDCFUznWCIwdRTyl/"
       "p9SdHVrsrzZuPMCNqZjnpakIni6upw==",
       "f6c375d51d4c22a7a850e185a0d7ddda85173f89dbbeb3262aa7971e3bd670b5",
       29001},
      {"claude-code-linux-x64-2.1.296",
       "sha512-+m01urgelnI+VJxPaKPEK0wixgq42uZ8PeCaUk5tX/8YoDBvSmC/"
       "REVQG2jQfJAr8dxunpjJ600FvLrcj1WWTw==",
       "eef5a2e2b09a5e7d2ce784d1b3ba335ae7fc6c7f6256c802a0ebf2c21e4fd0e1",
       114864541}};
  for (const auto &C : Cases) {
    const auto Base = std::string(Directory) + "/" + C.Name;
    const auto Original = capture(Base + ".tgz", Limits{});
    const auto Metadata = capture(Base + ".registry.json", Limits{});
    const auto &A = Original.Artifacts.front();
    ASSERT_EQ(A.BlobHash, C.SHA256);
    ASSERT_EQ(A.Content.size(), C.Bytes);
    const auto D = registryPackageIntegrity(Metadata.Artifacts.front());
    ASSERT_EQ(D.Value, C.SRI);
    const auto R = verifyPackageIntegrity(A, D);
    EXPECT_EQ(R.Status, "match");
    EXPECT_EQ(R.Algorithm, "sha512");
  }
}
#endif
} // namespace
