//===- ProcessObserver.h - Stopped guest process inspection -----*- C++ -*-===//
//
// NeverD Decompiler
//
//===----------------------------------------------------------------------===//
///
/// \file
/// Observation of a guest process at explicit execution boundaries. An
/// observer never executes guest code, never changes guest state and never
/// replenishes the workload budget; it only reads a stopped process and
/// selects where the next stop occurs.
///
//===----------------------------------------------------------------------===//
#ifndef NEVERD_EMULATION_PROCESSOBSERVER_H
#define NEVERD_EMULATION_PROCESSOBSERVER_H

#include "neverd/emulation/AddressSpace.h"
#include "neverd/emulation/ExecutionSession.h"
#include "neverd/emulation/ProcessSession.h"

#include <array>
#include <memory>
#include <optional>
#include <string>
#include <vector>

namespace neverd::emulation {
class ProcessRuntimeState;
/// One image known to the guest loader at the observed boundary.
struct ProcessModuleView {
  /// Guest basename as the loader records it.
  std::string Name;
  uint64_t Base, Size, Entry;
  /// The process image, as opposed to a dependency or system provider.
  bool Main;
  /// Bytes generated by the OS model rather than read from a guest file.
  bool Modeled;
};

/// One code address the guest loader can hand out for an export identity.
/// Several identities may share an address; each has its own record.
struct ProcessExportView {
  uint64_t Address;
  std::string Module, Name;
  std::optional<uint16_t> Ordinal;
};

/// The OS-owned stack allocation of the observed thread.
struct ProcessStackView {
  uint64_t Base, Size;
};

/// A live allocation owned by the process heap. The size is the requested
/// extent, excluding allocator padding; a zero-size allocation has at least
/// one byte. Addresses belong to this process.
struct ProcessHeapAllocationView {
  uint64_t Address, Size;
};

/// Dynamic local slots whose ownership or current-thread value survives.
/// Allocated zero-valued slots and nonzero cells without allocation records
/// both carry state. This is separate from the input image's static TLS.
struct ProcessDynamicThreadLocalState {
  uint64_t ThreadSlots = 0, FiberSlots = 0;
};

/// Integer ABI facts at a stopped entry boundary. They describe the current
/// return location and first three arguments, not a function signature or
/// evidence that a call instruction executed.
struct ProcessCallFrame {
  uint64_t ReturnAddress, ReturnStackPointer;
  std::array<uint64_t, 3> Arguments;
};

/// A stopped process. The view is valid only during the observer callback
/// that receives it and must not be retained.
class ProcessView {
public:
  virtual ~ProcessView();
  virtual GuestArchitecture architecture() const = 0;
  virtual llvm::Expected<RegisterValue> readRegister(CPURegister Register) = 0;
  /// Copy committed RAM independently of guest page permissions. Unmapped
  /// bytes and device mappings fail without a partial copy.
  virtual llvm::Error read(uint64_t Address,
                           llvm::MutableArrayRef<uint8_t> Bytes) = 0;
  /// Sorted layout coalesced by permissions and RAM/device kind.
  virtual llvm::Expected<std::vector<AddressMapping>> mappings() = 0;
  /// Resident images in loader registration order; the process image first.
  virtual std::vector<ProcessModuleView> modules() = 0;
  /// The caller's input image. A library workload has a separate modeled
  /// process image; its input is absent until the loader maps the library.
  /// The default selects the main image for ordinary process workloads.
  virtual std::optional<ProcessModuleView> inputModule();
  /// Absent when no accessible ABI return frame can be read. Observation
  /// must separately witness the matching continuation before using it.
  virtual llvm::Expected<std::optional<ProcessCallFrame>> callFrame() {
    return std::nullopt;
  }
  /// Every export identity currently bound to an OS-model entry address.
  virtual std::vector<ProcessExportView> exports() = 0;
  /// Execution belongs to the input's entry invocation, including calls it
  /// makes. A library uses its process-attach entry. False for other OS-owned
  /// initialization and teardown calls, or without invocation provenance.
  virtual bool programInvocation() const { return false; }
  /// Input-image initializers whose OS-owned startup calls returned normally.
  /// These addresses are execution evidence, not predicted callback targets.
  virtual std::vector<uint64_t> completedInitializers() const { return {}; }
  /// The current thread's stack allocation, if the profile owns it.
  virtual std::optional<ProcessStackView> stack() const { return std::nullopt; }
  /// Live heap allocations at this boundary. An empty vector establishes
  /// that none exist; std::nullopt means the profile supplies no contract.
  virtual std::optional<std::vector<ProcessHeapAllocationView>>
  heapAllocations() const {
    return std::nullopt;
  }
  /// Process-local pointer encodings witnessed by completed OS operations.
  /// These are values, not storage locations or proof of pointer types.
  /// Empty establishes no observed values; absent means no inventory contract.
  virtual std::optional<std::vector<uint64_t>> encodedPointers() const {
    return std::nullopt;
  }
  /// Dynamic thread/fiber-local state at this boundary. Zero counts establish
  /// no retained slots; absent means the profile supplies no inventory.
  virtual llvm::Expected<std::optional<ProcessDynamicThreadLocalState>>
  dynamicThreadLocalState() {
    return std::nullopt;
  }
  /// Immutable OS-owned objects at this exact stop. IncludeBacking requests
  /// allocation contents for materialization, rather than inventory only.
  /// Missing means the profile has no materialization contract, not an empty
  /// state.
  virtual llvm::Expected<std::shared_ptr<const ProcessRuntimeState>>
  runtimeState(bool IncludeBacking = false) {
    return std::shared_ptr<const ProcessRuntimeState>();
  }
  /// Number of OS service invocations so far, including calls still active.
  /// Missing provenance cannot establish that a helper has no OS effects.
  virtual std::optional<uint64_t> nativeCallCount() const {
    return std::nullopt;
  }
  /// Live input-image static TLS bytes of the current thread, excluding
  /// allocation padding. An empty vector means no data; std::nullopt means
  /// the profile supplies no TLS snapshot contract.
  virtual llvm::Expected<std::optional<std::vector<uint8_t>>>
  threadLocalMemory() {
    return std::nullopt;
  }
  /// The current instruction's decoded extent, using the CPU's fetch rules.
  /// Missing decoding support is an error, never a guessed instruction size.
  virtual llvm::Expected<uint32_t> instructionSize(uint64_t Address);
  /// No write or mapping change could have touched the RAM covered by the
  /// memory write watches installed for the preceding CPU run. False supplies
  /// no guarantee. Newly watched ranges still require an initial snapshot.
  virtual bool watchedMemoryUnchanged() const { return false; }
};

/// Receives a process at its start and at each execution watch.
class ProcessObserver {
public:
  virtual ~ProcessObserver();
  /// Images are mapped and linked and the initial thread exists; no guest
  /// instruction has executed. Returns the initial execution watches.
  virtual llvm::Expected<std::vector<ExecutionWatch>>
  started(ProcessView &Process) = 0;
  /// The process is suspended before the first instruction of a watched range
  /// at \p PC. Returning a watch set resumes with it; the reported instruction
  /// executes once without matching again. Returning std::nullopt ends the
  /// run with ProcessStopReason::Observer.
  virtual llvm::Expected<std::optional<std::vector<ExecutionWatch>>>
  watched(ProcessView &Process, uint64_t PC) = 0;
  /// The OS model has prepared a guest invocation or restored a suspended
  /// caller. The initial invocation is covered by started(). Returning a
  /// watch set replaces the current watches; std::nullopt keeps them.
  virtual llvm::Expected<std::optional<std::vector<ExecutionWatch>>>
  invoking(ProcessView &Process);
  /// The OS has identified an export gate, before API effects or an
  /// unsupported-export stop. Identity does not imply a modeled signature.
  /// ReturnAddress is absent when the ABI return location could not be read.
  virtual llvm::Error exporting(ProcessView &Process,
                                const ProcessExportView &Export,
                                std::optional<uint64_t> ReturnAddress);
  /// The model is about to resume the CPU. This includes changes made by OS
  /// services while stopped and committed guest writes that yielded the CPU.
  /// A returned set replaces execution watches; std::nullopt keeps them.
  virtual llvm::Expected<std::optional<std::vector<ExecutionWatch>>>
  resuming(ProcessView &Process);
  /// RAM ranges to invalidate after a guest write, through any physical alias.
  /// The model replaces these watches before each CPU resume.
  virtual std::vector<MemoryWriteWatch> writeWatches() const { return {}; }
};

/// As emulateProcess, under observation. Profiles without an observation
/// contract fail before execution rather than ignoring the observer.
llvm::Expected<ProcessResult> observeProcess(const std::filesystem::path &Path,
                                             ProcessProfile Profile,
                                             const ProcessOptions &Options,
                                             ProcessObserver &Observer);
} // namespace neverd::emulation
#endif
