//===- CEmitter.cpp - EVM to standalone C23 backend ---------------------===//

#include "neverd/evm/CEmitter.h"

#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"

#include <array>
#include <limits>

namespace neverd::evm {
namespace {

inline constexpr unsigned kEmitterLimbBits =
    std::numeric_limits<uint64_t>::digits;
inline constexpr unsigned kEmitterLimbCount = kWordBits / kEmitterLimbBits;

llvm::StringRef cExitStatusName(ExitStatus Status) {
  switch (Status) {
#define EVM_EXIT_STATUS(NAME, C_NAME, VALUE)                                   \
  case ExitStatus::NAME:                                                       \
    return #C_NAME;
#include "neverd/evm/EVMExitStatuses.def"
  }
  llvm_unreachable("invalid EVM exit status");
}

std::string wordExpression(const llvm::APInt &Value) {
  std::array<uint64_t, kEmitterLimbCount> Chunks{};
  for (unsigned I = 0; I < kEmitterLimbCount; ++I)
    Chunks[I] =
        Value.extractBitsAsZExtValue(kEmitterLimbBits, I * kEmitterLimbBits);
  std::string Text = "((evm_word)0)";
  for (unsigned I = 0; I < kEmitterLimbCount; ++I) {
    if (Chunks[I] == 0)
      continue;
    Text += " | ((evm_word)0x" + llvm::utohexstr(Chunks[I]) + "ULL";
    if (I != 0)
      Text += " << " + std::to_string(I * kEmitterLimbBits);
    Text += ")";
  }
  return "(" + Text + ")";
}

std::string nextStatement(const llvm::DenseSet<uint64_t> &InstructionPCs,
                          uint64_t NextPC) {
  if (InstructionPCs.contains(NextPC))
    return "goto pc_" + std::to_string(NextPC) + ";";
  return "return " + cExitStatusName(ExitStatus::Stopped).str() + ";";
}

std::string hostCall(Opcode Op, const std::vector<std::string> &Inputs) {
  std::string Text = kHostFunctionName.str() + "(environment, 0x" +
                     llvm::utohexstr(opcodeByte(Op)) + "u";
  for (size_t I = 0; I < maxHostOpcodeArguments(); ++I)
    Text += ", " + (I < Inputs.size() ? Inputs[I] : "(evm_word)0");
  return Text + ")";
}

std::string pureExpression(Opcode Op, const std::vector<std::string> &Inputs) {
  const std::string &A = Inputs[0];
  const std::string B = Inputs.size() > 1 ? Inputs[1] : "(evm_word)0";
  switch (Op) {
  case Opcode::ADD:
    return "(" + A + " + " + B + ")";
  case Opcode::MUL:
    return "(" + A + " * " + B + ")";
  case Opcode::SUB:
    return "(" + A + " - " + B + ")";
  case Opcode::DIV:
    return "evm_udiv(" + A + ", " + B + ")";
  case Opcode::SDIV:
    return "evm_sdiv(" + A + ", " + B + ")";
  case Opcode::MOD:
    return "evm_umod(" + A + ", " + B + ")";
  case Opcode::SMOD:
    return "evm_smod(" + A + ", " + B + ")";
  case Opcode::ADDMOD:
    return "evm_addmod(" + A + ", " + B + ", " + Inputs[2] + ")";
  case Opcode::MULMOD:
    return "evm_mulmod(" + A + ", " + B + ", " + Inputs[2] + ")";
  case Opcode::EXP:
    return "evm_exp(" + A + ", " + B + ")";
  case Opcode::SIGNEXTEND:
    return "evm_signextend(" + A + ", " + B + ")";
  case Opcode::LT:
    return "(evm_word)(" + A + " < " + B + ")";
  case Opcode::GT:
    return "(evm_word)(" + A + " > " + B + ")";
  case Opcode::SLT:
    return "(evm_word)((evm_sword)" + A + " < (evm_sword)" + B + ")";
  case Opcode::SGT:
    return "(evm_word)((evm_sword)" + A + " > (evm_sword)" + B + ")";
  case Opcode::EQ:
    return "(evm_word)(" + A + " == " + B + ")";
  case Opcode::ISZERO:
    return "(evm_word)(" + A + " == 0)";
  case Opcode::AND:
    return "(" + A + " & " + B + ")";
  case Opcode::OR:
    return "(" + A + " | " + B + ")";
  case Opcode::XOR:
    return "(" + A + " ^ " + B + ")";
  case Opcode::NOT:
    return "(~" + A + ")";
  case Opcode::BYTE:
    return "evm_byte(" + A + ", " + B + ")";
  case Opcode::SHL:
    return "evm_shl(" + A + ", " + B + ")";
  case Opcode::SHR:
    return "evm_shr(" + A + ", " + B + ")";
  case Opcode::SAR:
    return "evm_sar(" + A + ", " + B + ")";
  case Opcode::CLZ:
    return "evm_clz(" + A + ")";
  default:
    llvm_unreachable("unhandled EVM ALU opcode in C backend");
  }
}

} // namespace

llvm::Expected<std::string> emitC(const EVMProgram &Program,
                                  const CEmitterOptions &Options) {
  std::string Text;
  llvm::raw_string_ostream OS(Text);
  llvm::DenseSet<uint64_t> InstructionPCs;
  InstructionPCs.reserve(Program.Low.Instructions.size());
  for (const LowInstruction &Instruction : Program.Low.Instructions)
    InstructionPCs.insert(Instruction.PC);
  OS << "/* Generated by NeverD from EVM bytecode.\n"
        " * This is a semantic reconstruction, not the original source.\n"
        " * Implement "
     << kHostFunctionName
     << " for memory, storage, calls, logs,\n"
        " * hashing, calldata, block context, return and revert effects.\n"
        " * Callback arguments are in pop order: a0 is the original stack\n"
        " * top, and the return value is the first value pushed by the opcode. "
        "*/\n"
        "#include <limits.h>\n"
        "#include <stddef.h>\n"
        "#include <stdint.h>\n\n"
     << "#define NEVERD_EVM_BITS_PER_BYTE " << kBitsPerByte << "u\n"
     << "#define NEVERD_EVM_BYTE_MAX " << kByteMax << "u\n"
     << "#define NEVERD_EVM_WORD_BITS " << kWordBits << "u\n"
     << "#define NEVERD_EVM_WIDE_WORD_BITS " << kWideWordBits << "u\n"
     << "#define NEVERD_EVM_WORD_BYTES " << kWordBytes << "u\n"
     << "#define NEVERD_EVM_WORD_MAX_BYTE_INDEX " << kWordMaxByteIndex << "u\n"
     << "#define NEVERD_EVM_WORD_MSB " << kWordMostSignificantBit << "u\n"
     << "#define NEVERD_EVM_STACK_LIMIT " << kStackLimit
     << "u\n\n"
        "_Static_assert(CHAR_BIT == NEVERD_EVM_BITS_PER_BYTE, "
        "\"NeverD EVM output requires "
     << kBitsPerByte
     << "-bit bytes\");\n"
        "typedef unsigned _BitInt(NEVERD_EVM_WORD_BITS) evm_word;\n"
        "typedef signed _BitInt(NEVERD_EVM_WORD_BITS) evm_sword;\n"
        "typedef unsigned _BitInt(NEVERD_EVM_WIDE_WORD_BITS) evm_wide;\n\n"
        "enum neverd_evm_status {\n";
#define EVM_EXIT_STATUS(NAME, C_NAME, VALUE)                                   \
  OS << "  " #C_NAME " = "                                                     \
     << static_cast<unsigned>(exitStatusCode(ExitStatus::NAME)) << ",\n";
#include "neverd/evm/EVMExitStatuses.def"
  OS << "};\n"
        "struct neverd_evm_env;\n"
        "extern evm_word "
     << kHostFunctionName << "(struct neverd_evm_env *, uint8_t";
  for (size_t I = 0; I < maxHostOpcodeArguments(); ++I)
    OS << ", evm_word";
  OS << ");\n"
        "extern void "
     << kTraceFunctionName
     << "(struct neverd_evm_env *, uint64_t, "
        "uint8_t);\n\n"
        "static _Noreturn void evm_fault(void) { __builtin_trap(); }\n"
        "static void evm_push(evm_word *stack, size_t *sp, evm_word value) "
        "{ if (*sp >= NEVERD_EVM_STACK_LIMIT) evm_fault(); "
        "stack[(*sp)++] = value; }\n"
        "static evm_word evm_pop(evm_word *stack, size_t *sp) "
        "{ if (*sp == 0) evm_fault(); return stack[--(*sp)]; }\n"
        "static evm_word evm_peek(evm_word *stack, size_t sp, size_t depth) "
        "{ if (sp < depth) evm_fault(); return stack[sp - depth]; }\n"
        "static void evm_swap(evm_word *stack, size_t sp, size_t depth) "
        "{ if (sp <= depth) evm_fault(); evm_word t = stack[sp - 1]; "
        "stack[sp - 1] = stack[sp - depth - 1]; stack[sp - depth - 1] = t; }\n"
        "static evm_word evm_udiv(evm_word a, evm_word b) "
        "{ return b == 0 ? 0 : a / b; }\n"
        "static evm_word evm_umod(evm_word a, evm_word b) "
        "{ return b == 0 ? 0 : a % b; }\n"
        "static evm_word evm_sdiv(evm_word a, evm_word b) { "
        "evm_sword sa = (evm_sword)a, sb = (evm_sword)b; "
        "evm_sword min = (evm_sword)((evm_word)1 << NEVERD_EVM_WORD_MSB); "
        "if (sb == 0) return 0; if (sa == min && sb == -1) return a; "
        "return (evm_word)(sa / sb); }\n"
        "static evm_word evm_smod(evm_word a, evm_word b) { "
        "evm_sword sa = (evm_sword)a, sb = (evm_sword)b; "
        "evm_sword min = (evm_sword)((evm_word)1 << NEVERD_EVM_WORD_MSB); "
        "if (sb == 0 || (sa == min && sb == -1)) return 0; "
        "return (evm_word)(sa % sb); }\n"
        "static evm_word evm_addmod(evm_word a, evm_word b, evm_word m) "
        "{ return m == 0 ? 0 : (evm_word)(((evm_wide)a + (evm_wide)b) % "
        "(evm_wide)m); }\n"
        "static evm_word evm_mulmod(evm_word a, evm_word b, evm_word m) "
        "{ return m == 0 ? 0 : (evm_word)(((evm_wide)a * (evm_wide)b) % "
        "(evm_wide)m); }\n"
        "static evm_word evm_exp(evm_word base, evm_word exponent) { "
        "evm_word result = 1; while (exponent != 0) { if ((exponent & 1) != 0) "
        "result *= base; exponent >>= 1; base *= base; } return result; }\n"
        "static evm_word evm_signextend(evm_word k, evm_word value) { "
        "if (k >= NEVERD_EVM_WORD_BYTES) return value; unsigned bit = "
        "(unsigned)k * NEVERD_EVM_BITS_PER_BYTE + "
        "(NEVERD_EVM_BITS_PER_BYTE - 1u); "
        "if (bit == NEVERD_EVM_WORD_MSB) return value; "
        "evm_word low = (((evm_word)1 << "
        "(bit + 1u)) - 1); return ((value >> bit) & 1) ? (value | ~low) : "
        "(value & low); }\n"
        "static evm_word evm_byte(evm_word k, evm_word value) "
        "{ return k >= NEVERD_EVM_WORD_BYTES ? 0 : "
        "(value >> ((NEVERD_EVM_WORD_MAX_BYTE_INDEX - (unsigned)k) * "
        "NEVERD_EVM_BITS_PER_BYTE)) & NEVERD_EVM_BYTE_MAX; "
        "}\n"
        "static evm_word evm_shl(evm_word s, evm_word v) "
        "{ return s >= NEVERD_EVM_WORD_BITS ? 0 : v << (unsigned)s; }\n"
        "static evm_word evm_shr(evm_word s, evm_word v) "
        "{ return s >= NEVERD_EVM_WORD_BITS ? 0 : v >> (unsigned)s; }\n"
        "static evm_word evm_sar(evm_word s, evm_word v) { "
        "evm_word negative = v >> NEVERD_EVM_WORD_MSB; "
        "if (s >= NEVERD_EVM_WORD_BITS) return negative ? ~(evm_word)0 : 0; "
        "evm_word shifted = v >> (unsigned)s; "
        "if (!negative || s == 0) return shifted; "
        "return shifted | (~(evm_word)0 << "
        "(NEVERD_EVM_WORD_BITS - (unsigned)s)); }\n"
        "static evm_word evm_clz(evm_word v) { evm_word n = 0; "
        "if (v == 0) return NEVERD_EVM_WORD_BITS; "
        "while ((v >> NEVERD_EVM_WORD_MSB) == 0) { ++n; v <<= 1; } "
        "return n; }\n\n";

  if (Options.EmitRecoveredComments)
    for (const auto &Function : Program.High.Functions)
      OS << "/* recovered selector 0x"
         << llvm::format_hex_no_prefix(Function.Selector, kSelectorHexDigits,
                                       false)
         << " -> " << Function.Name << " at pc 0x"
         << llvm::utohexstr(Function.EntryPC) << " */\n";

  OS << "int " << Options.FunctionName
     << "(struct neverd_evm_env *environment) {\n"
        "  evm_word evm_stack[NEVERD_EVM_STACK_LIMIT] = {0};\n"
        "  size_t evm_sp = 0;\n";
  if (InstructionPCs.contains(kEntryPC))
    OS << "  goto pc_" << kEntryPC << ";\n\n";
  else
    OS << "  (void)environment;\n"
       << "  return " << cExitStatusName(ExitStatus::Stopped) << ";\n";

  for (const auto &Instruction : Program.Low.Instructions) {
    const uint64_t PC = Instruction.PC;
    const Opcode Op = Instruction.opcode();
    OS << "pc_" << PC << ": { /* " << Instruction.Info.Name << " */\n";
    if (Options.EmitTraceHooks)
      OS << "  " << kTraceFunctionName << "(environment, " << PC << "u, 0x"
         << llvm::utohexstr(opcodeByte(Op)) << "u);\n";

    if (!Instruction.isKnown() || Instruction.is(Opcode::INVALID)) {
      OS << "  evm_fault();\n}\n";
      continue;
    }
    if (Instruction.is(Opcode::STOP)) {
      OS << "  return " << cExitStatusName(ExitStatus::Stopped) << ";\n}\n";
      continue;
    }
    if (Instruction.isPush()) {
      OS << "  evm_push(evm_stack, &evm_sp, "
         << wordExpression(Instruction.Immediate) << ");\n  "
         << nextStatement(InstructionPCs, Instruction.NextPC) << "\n}\n";
      continue;
    }
    if (Instruction.isDup()) {
      OS << "  evm_push(evm_stack, &evm_sp, evm_peek(evm_stack, evm_sp, "
         << static_cast<unsigned>(dupDepth(Op)) << "u));\n  "
         << nextStatement(InstructionPCs, Instruction.NextPC) << "\n}\n";
      continue;
    }
    if (Instruction.isSwap()) {
      OS << "  evm_swap(evm_stack, evm_sp, "
         << static_cast<unsigned>(swapDepth(Op)) << "u);\n  "
         << nextStatement(InstructionPCs, Instruction.NextPC) << "\n}\n";
      continue;
    }
    if (Instruction.isJump()) {
      OS << "  evm_word destination = evm_pop(evm_stack, &evm_sp);\n";
      if (Op == Opcode::JUMPI)
        OS << "  evm_word condition = evm_pop(evm_stack, &evm_sp);\n"
              "  if (condition == 0) { "
           << nextStatement(InstructionPCs, Instruction.NextPC) << " }\n";
      OS << "  switch (destination) {\n";
      for (uint64_t Target : Program.Low.JumpDestinations)
        OS << "  case " << Target << ": goto pc_" << Target << ";\n";
      OS << "  default: evm_fault();\n  }\n}\n";
      continue;
    }

    std::vector<std::string> Inputs;
    for (uint8_t I = 0; I < Instruction.Info.StackInputs; ++I) {
      std::string Name = "a" + std::to_string(I);
      OS << "  evm_word " << Name << " = evm_pop(evm_stack, &evm_sp);\n";
      Inputs.push_back(std::move(Name));
    }
    if (Op == Opcode::POP || Op == Opcode::JUMPDEST) {
      OS << "  " << nextStatement(InstructionPCs, Instruction.NextPC)
         << "\n}\n";
      continue;
    }
    if (Op == Opcode::PC || Op == Opcode::CODESIZE) {
      const uint64_t Value = Op == Opcode::PC ? PC : Program.Low.Code.size();
      OS << "  evm_push(evm_stack, &evm_sp, (evm_word)" << Value << "u);\n  "
         << nextStatement(InstructionPCs, Instruction.NextPC) << "\n}\n";
      continue;
    }

    const bool HasInlineALULowering = isALU(Instruction.Info);
    const std::string Output = HasInlineALULowering ? pureExpression(Op, Inputs)
                                                    : hostCall(Op, Inputs);
    if (Instruction.Info.StackOutputs != 0)
      OS << "  evm_word result = " << Output << ";\n";
    else if (!HasInlineALULowering)
      OS << "  (void)" << Output << ";\n";

    if (Op == Opcode::RETURN || Op == Opcode::REVERT ||
        Op == Opcode::SELFDESTRUCT) {
      OS << "  return "
         << (Op == Opcode::RETURN ? cExitStatusName(ExitStatus::Returned)
             : Op == Opcode::REVERT
                 ? cExitStatusName(ExitStatus::Reverted)
                 : cExitStatusName(ExitStatus::SelfDestructed))
         << ";\n}\n";
      continue;
    }
    if (Instruction.Info.IsTerminator) {
      OS << "  return " << cExitStatusName(ExitStatus::Stopped) << ";\n}\n";
      continue;
    }
    if (Instruction.Info.StackOutputs != 0)
      OS << "  evm_push(evm_stack, &evm_sp, result);\n";
    OS << "  " << nextStatement(InstructionPCs, Instruction.NextPC) << "\n}\n";
  }
  OS << "}\n";
  return Text;
}

} // namespace neverd::evm
