//===- SBFCEmitter.cpp - Solana SBF to portable C backend -----------------===//
//
// NeverD Decompiler
//
//===----------------------------------------------------------------------===//
///
/// \file
/// Drives C emission for a recovered SBF program: decides which arithmetic
/// helpers the program needs, writes the runtime interface and the recovered
/// constants, then renders the body either as a structured function or as a
/// program-counter dispatch switch.
///
//===----------------------------------------------------------------------===//

#include "neverd/sbf/emit/SBFCEmitter.h"

#include "SBFCEmitterDetail.h"

#include "neverd/sbf/analysis/SBFAnalyzer.h"
#include "neverd/sbf/analysis/SBFStructuredCFG.h"

#include "llvm/Support/raw_ostream.h"

#include <cstddef>
#include <map>
#include <optional>
#include <string>
#include <utility>

namespace neverd::sbf {

using namespace c_emitter_detail;

llvm::Expected<std::string> emitC(const SBFProgram &Program,
                                  const CEmitterOptions &Options) {
  if (llvm::Error Error = validateVMConfig(Program.Config))
    return std::move(Error);
  if (Program.Med.Instructions.empty())
    return llvm::make_error<llvm::StringError>(
        "sbf: cannot emit C for an empty MedIR",
        llvm::inconvertibleErrorCode());

  std::map<size_t, const MedInstruction *> BySlot;
  for (const MedInstruction &Instruction : Program.Med.Instructions)
    BySlot[Instruction.Slot] = &Instruction;
  const std::optional<StructuredControlFlow> Structured =
      Options.PreferStructuredControlFlow
          ? buildStructuredControlFlow(Program)
          : std::optional<StructuredControlFlow>{};

  bool NeedsSignExtension = false;
  bool NeedsSignedCompare32 = false;
  bool NeedsSignedCompare64 = false;
  bool NeedsArithmeticShift32 = false;
  bool NeedsArithmeticShift64 = false;
  bool NeedsUnsignedHighMultiply = false;
  bool NeedsSignedHighMultiply = false;
  bool NeedsByteSwap = false;
  bool NeedsSignedDivision = false;
  bool NeedsIndirectCall = false;
  for (const MedInstruction &Instruction : Program.Med.Instructions) {
    NeedsSignExtension |=
        Instruction.Semantics.Result == ResultExtension::Sign32;
    const bool SignedCompare =
        Instruction.Op == Operation::SGt || Instruction.Op == Operation::SGe ||
        Instruction.Op == Operation::SLt || Instruction.Op == Operation::SLe;
    NeedsSignedCompare32 |= SignedCompare && Instruction.Width == kWordBitWidth;
    NeedsSignedCompare64 |=
        SignedCompare && Instruction.Width == kDoubleWordBitWidth;
    NeedsArithmeticShift32 |=
        Instruction.Op == Operation::ARSh && Instruction.Width == kWordBitWidth;
    NeedsArithmeticShift64 |= Instruction.Op == Operation::ARSh &&
                              Instruction.Width == kDoubleWordBitWidth;
    NeedsUnsignedHighMultiply |= Instruction.Op == Operation::UHighMul ||
                                 Instruction.Op == Operation::SHighMul;
    NeedsSignedHighMultiply |= Instruction.Op == Operation::SHighMul;
    NeedsByteSwap |= Instruction.Op == Operation::EndianBE;
    NeedsSignedDivision |=
        Instruction.Op == Operation::SDiv || Instruction.Op == Operation::SRem;
    NeedsIndirectCall |= Instruction.Op == Operation::CallX;
  }

  std::string Buffer;
  llvm::raw_string_ostream OS(Buffer);
  OS << "/* Generated by NeverD from "
     << versionDisplayName(Program.Low.TheVersion)
     << ". */\n"
        "#include <stddef.h>\n#include <stdint.h>\n#include <limits.h>\n\n"
        "typedef enum neverd_sbf_status {\n"
        "  NEVERD_SBF_OK = 0, NEVERD_SBF_INVALID_INSTRUCTION,\n"
        "  NEVERD_SBF_MEMORY_ACCESS, NEVERD_SBF_DIVIDE_BY_ZERO,\n"
        "  NEVERD_SBF_DIVIDE_OVERFLOW, NEVERD_SBF_CALL_DEPTH,\n"
        "  NEVERD_SBF_UNKNOWN_SYSCALL, NEVERD_SBF_UNKNOWN_FUNCTION,\n"
        "  NEVERD_SBF_EXECUTION_OVERRUN\n"
        "} neverd_sbf_status;\n\n"
        "typedef struct neverd_sbf_environment {\n"
        "  void *context;\n"
        "  int (*load)(void *, uint64_t, uint32_t, uint64_t *);\n"
        "  int (*store)(void *, uint64_t, uint32_t, uint64_t);\n"
        "  int (*syscall)(void *, uint32_t";
  for (unsigned Index = 0; Index < kArgumentRegisterCount; ++Index)
    OS << ", uint64_t";
  OS << ", uint64_t *);\n"
        "} neverd_sbf_environment;\n\n"
        "enum { NEVERD_SBF_REGISTER_COUNT = "
     << kRegisterCount << ", NEVERD_SBF_RETURN_REGISTER = " << kReturnRegister
     << ", NEVERD_SBF_INPUT_REGISTER = " << kFirstArgumentRegister
     << ", NEVERD_SBF_INSTRUCTION_DATA_REGISTER = " << kInstructionDataRegister
     << ", NEVERD_SBF_FRAME_POINTER = " << kFramePointerRegister
     << ", NEVERD_SBF_FIRST_SAVED_REGISTER = " << kFirstCalleeSavedRegister
     << ", NEVERD_SBF_SAVED_REGISTERS = " << kCalleeSavedRegisterCount
     << ", NEVERD_SBF_MAX_CALL_DEPTH = " << Program.Config.MaxCallDepth
     << " };\n"
        "#define NEVERD_SBF_TEXT_ADDRESS "
     << word(Program.Low.TextAddress)
     << "\n"
        "#define NEVERD_SBF_INSTRUCTION_SIZE UINT64_C("
     << kInstructionSize
     << ")\n"
        "#define NEVERD_SBF_INSTRUCTION_COUNT UINT32_C("
     << Program.Low.Instructions.size()
     << ")\n"
        "#define NEVERD_SBF_STACK_START "
     << word(kStackStart)
     << "\n"
        "#define NEVERD_SBF_STACK_FRAME_SIZE UINT64_C("
     << Program.Config.StackFrameSize
     << ")\n"
        "#define NEVERD_SBF_STACK_SIZE UINT64_C("
     << stackSize(Program.Config) << ")\n\n";

  if (NeedsSignExtension)
    OS << "static uint64_t nd_sext32(uint32_t v) { return (v & "
          "UINT32_C(0x80000000)) ? (UINT64_C(0xffffffff00000000) | v) : v; }\n";
  if (NeedsSignedCompare32)
    OS << "static int nd_sgt32(uint32_t a, uint32_t b) { return (a ^ "
          "UINT32_C(0x80000000)) > (b ^ UINT32_C(0x80000000)); }\n";
  if (NeedsSignedCompare64)
    OS << "static int nd_sgt64(uint64_t a, uint64_t b) { return (a ^ "
          "UINT64_C(0x8000000000000000)) > (b ^ "
          "UINT64_C(0x8000000000000000)); }\n";
  if (NeedsArithmeticShift32)
    OS << "static uint32_t nd_ashr32(uint32_t v, uint64_t s) { unsigned n = "
          "(unsigned)s & 31u; if (!n) return v; return (v >> n) | ((v & "
          "UINT32_C(0x80000000)) ? (~UINT32_C(0) << (32u - n)) : 0); }\n";
  if (NeedsArithmeticShift64)
    OS << "static uint64_t nd_ashr64(uint64_t v, uint64_t s) { unsigned n = "
          "(unsigned)s & 63u; if (!n) return v; return (v >> n) | ((v & "
          "UINT64_C(0x8000000000000000)) ? (~UINT64_C(0) << (64u - n)) : 0); "
          "}\n";
  if (NeedsUnsignedHighMultiply)
    OS << "static uint64_t nd_umulh64(uint64_t a, uint64_t b) { uint64_t a0 "
          "= (uint32_t)a, a1 = a >> 32, b0 = (uint32_t)b, b1 = b >> 32; "
          "uint64_t w0 = a0*b0, t = a1*b0 + (w0 >> 32), w1 = (uint32_t)t, "
          "w2 = t >> 32; w1 += a0*b1; return a1*b1 + w2 + (w1 >> 32); }\n";
  if (NeedsSignedHighMultiply)
    OS << "static uint64_t nd_smulh64(uint64_t a, uint64_t b) { return "
          "nd_umulh64(a,b) - ((a >> 63) ? b : 0) - ((b >> 63) ? a : 0); }\n";
  if (NeedsByteSwap)
    OS << "static uint64_t nd_bswap(uint64_t v, unsigned bits) { if (bits == "
          "16) return ((v & 0xffu) << 8) | ((v >> 8) & 0xffu); if (bits == "
          "32) { v = ((v & UINT64_C(0x00ff00ff)) << 8) | ((v >> 8) & "
          "UINT64_C(0x00ff00ff)); return (v << 16) | (v >> 16); } v = ((v "
          "& UINT64_C(0x00ff00ff00ff00ff)) << 8) | ((v >> 8) & "
          "UINT64_C(0x00ff00ff00ff00ff)); v = ((v & "
          "UINT64_C(0x0000ffff0000ffff)) << 16) | ((v >> 16) & "
          "UINT64_C(0x0000ffff0000ffff)); return (v << 32) | (v >> 32); }\n";
  if (NeedsSignedDivision)
    OS << "static uint64_t nd_sdivrem(uint64_t a, uint64_t b, unsigned bits, "
          "int rem, int *fault) { uint64_t mask = bits == 32 ? UINT32_MAX : "
          "UINT64_MAX, sign = bits == 32 ? (UINT64_C(1)<<31) : "
          "(UINT64_C(1)<<63); a &= mask; b &= mask; if (!b) { *fault = "
          "NEVERD_SBF_DIVIDE_BY_ZERO; return 0; } if (a == sign && b == mask) "
          "{ *fault = NEVERD_SBF_DIVIDE_OVERFLOW; return 0; } { int na = "
          "(a&sign)!=0, nb=(b&sign)!=0; uint64_t ua=na?((~a+1)&mask):a, "
          "ub=nb?((~b+1)&mask):b, value=rem?(ua%ub):(ua/ub); if ((rem?na:"
          "(na!=nb)) && value) value=(~value+1)&mask; return value; } }\n";
  OS << "\n";

  if (Options.IncludeAnalysisComments) {
    OS << "/* Recovered: " << Program.High.Functions.size() << " function(s), "
       << Program.High.Syscalls.size() << " syscall site(s), "
       << Program.High.Regions.size() << " structured region(s). */\n";
    for (const Region &Region : Program.High.Regions)
      OS << "/* " << (Region.Kind == RegionKind::Loop ? "loop" : "if")
         << " at block_" << Region.HeaderBlock << " */\n";
  }

  // The loader hands the program the input buffer and, on a runtime that has
  // activated it, the instruction data. A callable that only takes the first
  // cannot reproduce a program that reads the second.
  OS << "neverd_sbf_status " << Options.FunctionName
     << "(neverd_sbf_environment *env, uint64_t input, "
        "uint64_t instruction_data, uint64_t *result) {\n"
        "  (void)env;\n"
        "  (void)result;\n"
        "  uint64_t r[NEVERD_SBF_REGISTER_COUNT] = {0};\n";
  if (!Structured)
    OS << "  uint64_t "
          "saved[NEVERD_SBF_MAX_CALL_DEPTH][NEVERD_SBF_SAVED_REGISTERS] = "
          "{{0}};\n"
          "  uint64_t saved_fp[NEVERD_SBF_MAX_CALL_DEPTH] = {0};\n"
          "  uint32_t return_pc[NEVERD_SBF_MAX_CALL_DEPTH] = {0};\n"
          "  size_t depth = 0, i = 0; uint32_t pc = "
       << Program.Low.EntrySlot << ";\n";
  OS << "  r[NEVERD_SBF_INPUT_REGISTER] = input; "
        "r[NEVERD_SBF_INSTRUCTION_DATA_REGISTER] = instruction_data; "
        "r[NEVERD_SBF_FRAME_POINTER] = NEVERD_SBF_STACK_START "
        "+ "
     << (versionHasFeature(Program.Low.TheVersion,
                           VersionFeature::ManualStackFrames)
             ? "NEVERD_SBF_STACK_SIZE"
             : "NEVERD_SBF_STACK_FRAME_SIZE")
     << ";\n";
  if (Structured) {
    if (!emitStructuredNodes(OS, Program, BySlot, Structured->Body, "  "))
      return llvm::make_error<llvm::StringError>(
          "sbf: structured C emission rejected its validated control-flow plan",
          llvm::inconvertibleErrorCode());
    OS << "  return NEVERD_SBF_EXECUTION_OVERRUN;\n}\n";
    return Buffer;
  }

  OS << "  for (;;) {\n    switch (pc) {\n";
  for (size_t Slot = 0; Slot < Program.Low.Instructions.size(); ++Slot) {
    if (Program.Low.Instructions[Slot].IsContinuation) {
      if (NeedsIndirectCall)
        OS << "      case " << Slot
           << ": return NEVERD_SBF_INVALID_INSTRUCTION;\n";
      continue;
    }
    auto It = BySlot.find(Slot);
    if (It == BySlot.end()) {
      OS << "      case " << Slot
         << ": return NEVERD_SBF_INVALID_INSTRUCTION;\n";
      continue;
    }
    emitInstruction(OS, *It->second, Program);
  }
  OS << "      default: return NEVERD_SBF_EXECUTION_OVERRUN;\n"
        "    }\n  }\n}\n";
  return Buffer;
}

} // namespace neverd::sbf
