//===- SBFRustEmitter.cpp - Solana SBF to safe Rust backend ---------------===//
//
// NeverD Decompiler
//
//===----------------------------------------------------------------------===//
///
/// \file
/// Drives Rust emission for a recovered SBF program: declares the
/// environment trait and the recovered constants, decides which call-frame
/// state the program needs, then renders the body either as a structured
/// function or as a program-counter dispatch match.
///
//===----------------------------------------------------------------------===//

#include "neverd/sbf/emit/SBFRustEmitter.h"

#include "SBFRustEmitterDetail.h"

#include "neverd/sbf/analysis/SBFStructuredCFG.h"

#include "llvm/Support/raw_ostream.h"

#include <cstddef>
#include <map>
#include <optional>
#include <string>
#include <utility>

namespace neverd::sbf {

using namespace rust_emitter_detail;

llvm::Expected<std::string> emitRust(const SBFProgram &Program,
                                     const RustEmitterOptions &Options) {
  if (llvm::Error Error = validateVMConfig(Program.Config))
    return std::move(Error);
  if (Program.Med.Instructions.empty())
    return llvm::make_error<llvm::StringError>(
        "sbf: cannot emit Rust for an empty MedIR",
        llvm::inconvertibleErrorCode());

  std::map<size_t, const MedInstruction *> BySlot;
  for (const MedInstruction &Instruction : Program.Med.Instructions)
    BySlot[Instruction.Slot] = &Instruction;
  const std::optional<StructuredControlFlow> Structured =
      Options.PreferStructuredControlFlow
          ? buildStructuredControlFlow(Program)
          : std::optional<StructuredControlFlow>{};

  bool NeedsSignExtension = false;
  bool NeedsCallFrames = false;
  bool NeedsIndirectCall = false;
  for (const MedInstruction &Instruction : Program.Med.Instructions) {
    NeedsSignExtension |=
        Instruction.Semantics.Result == ResultExtension::Sign32;
    NeedsCallFrames |= Instruction.Call == CallKind::Internal ||
                       Instruction.Op == Operation::CallX;
    NeedsIndirectCall |= Instruction.Op == Operation::CallX;
  }

  std::string Buffer;
  llvm::raw_string_ostream OS(Buffer);
  OS << "// Generated by NeverD from "
     << versionDisplayName(Program.Low.TheVersion)
     << ".\n"
        "#![allow(clippy::unusual_byte_groupings)]\n\n"
        "#[derive(Clone, Copy, Debug, Eq, PartialEq)]\n"
        "pub enum SbfError { InvalidInstruction, MemoryAccess, DivideByZero, "
        "DivideOverflow, CallDepth, UnknownSyscall, UnknownFunction, "
        "ExecutionOverrun }\n\n"
        "pub trait SbfEnvironment {\n"
        "    fn load(&mut self, address: u64, width: u8) -> Result<u64, "
        "SbfError>;\n"
        "    fn store(&mut self, address: u64, width: u8, value: u64) -> "
        "Result<(), SbfError>;\n"
        "    fn syscall(&mut self, hash: u32, args: [u64; "
     << kArgumentRegisterCount
     << "]) -> Result<u64, SbfError>;\n"
        "}\n\n"
        "const REGISTER_COUNT: usize = "
     << kRegisterCount
     << ";\nconst RETURN_REGISTER: usize = " << kReturnRegister
     << ";\nconst INPUT_REGISTER: usize = " << kFirstArgumentRegister
     << ";\nconst INSTRUCTION_DATA_REGISTER: usize = "
     << kInstructionDataRegister
     << ";\nconst FRAME_POINTER: usize = " << kFramePointerRegister << ";\n";
  if (!Structured)
    OS << "const FIRST_SAVED: usize = " << kFirstCalleeSavedRegister
       << ";\nconst SAVED_REGISTERS: usize = " << kCalleeSavedRegisterCount
       << ";\nconst MAX_CALL_DEPTH: usize = " << Program.Config.MaxCallDepth
       << ";\n";
  if (NeedsIndirectCall)
    OS << "const INSTRUCTION_SIZE: u64 = " << kInstructionSize
       << ";\nconst TEXT_ADDRESS: u64 = " << word(Program.Low.TextAddress)
       << ";\nconst INSTRUCTION_COUNT: usize = "
       << Program.Low.Instructions.size() << ";\n";
  OS << "const STACK_START: u64 = " << word(kStackStart) << ";\n";
  if (versionHasFeature(Program.Low.TheVersion,
                        VersionFeature::ManualStackFrames))
    OS << "const STACK_SIZE: u64 = " << stackSize(Program.Config) << "u64;\n\n";
  else
    OS << "const STACK_FRAME_SIZE: u64 = " << Program.Config.StackFrameSize
       << "u64;\n\n";
  if (NeedsSignExtension)
    OS << "#[inline] fn sext32(value: u32) -> u64 { (value as i32 as i64) as "
          "u64 }\n\n";

  if (Options.IncludeAnalysisComments) {
    OS << "// Recovered " << Program.High.Functions.size() << " function(s), "
       << Program.High.Syscalls.size() << " syscall site(s), and "
       << Program.High.Regions.size() << " structured region(s).\n";
    for (const Region &Region : Program.High.Regions)
      OS << "// " << (Region.Kind == RegionKind::Loop ? "loop" : "if")
         << " at block_" << Region.HeaderBlock << "\n";
  }

  // The loader hands the program the input buffer and, on a runtime that has
  // activated it, the instruction data. A callable that only takes the first
  // cannot reproduce a program that reads the second.
  OS << "pub fn " << Options.FunctionName
     << "<E: SbfEnvironment>(env: &mut E, input: u64, instruction_data: u64) "
        "-> Result<u64, SbfError> "
        "{\n"
        "    let _ = &mut *env;\n"
        "    let mut r = [0u64; REGISTER_COUNT];\n";
  if (!Structured) {
    OS << "    let ";
    if (NeedsCallFrames)
      OS << "mut ";
    OS << "saved = [[0u64; SAVED_REGISTERS]; MAX_CALL_DEPTH];\n"
          "    let ";
    if (NeedsCallFrames)
      OS << "mut ";
    OS << "saved_fp = [0u64; MAX_CALL_DEPTH];\n"
          "    let ";
    if (NeedsCallFrames)
      OS << "mut ";
    OS << "return_pc = [0usize; MAX_CALL_DEPTH];\n"
          "    let mut depth = 0usize;\n"
          "    let mut pc = "
       << Program.Low.EntrySlot << "usize;\n";
  }
  OS << "    r[INPUT_REGISTER] = input; "
        "r[INSTRUCTION_DATA_REGISTER] = instruction_data; "
        "r[FRAME_POINTER] = STACK_START + "
     << (versionHasFeature(Program.Low.TheVersion,
                           VersionFeature::ManualStackFrames)
             ? "STACK_SIZE"
             : "STACK_FRAME_SIZE")
     << ";\n";
  if (Structured) {
    if (!emitStructuredNodes(OS, Program, BySlot, Structured->Body, "    "))
      return llvm::make_error<llvm::StringError>(
          "sbf: structured Rust emission rejected its validated control-flow "
          "plan",
          llvm::inconvertibleErrorCode());
    OS << "}\n";
    return Buffer;
  }

  OS << "    loop {\n        match pc {\n";
  for (size_t Slot = 0; Slot < Program.Low.Instructions.size(); ++Slot) {
    if (Program.Low.Instructions[Slot].IsContinuation) {
      if (NeedsIndirectCall)
        OS << "            " << Slot
           << " => return Err(SbfError::InvalidInstruction),\n";
      continue;
    }
    auto It = BySlot.find(Slot);
    if (It == BySlot.end()) {
      OS << "            " << Slot
         << " => return Err(SbfError::InvalidInstruction),\n";
      continue;
    }
    emitInstruction(OS, *It->second, Program);
  }
  OS << "            _ => return Err(SbfError::ExecutionOverrun),\n"
        "        }\n    }\n}\n";
  return Buffer;
}

} // namespace neverd::sbf
