//===- ARM32_AutoRoundTripTests.cpp - Auto-generated roundtrip tests --*- C++ -*-===//
//
// NeverD Decompiler
//
//===----------------------------------------------------------------------===//
//
// AUTO-GENERATED by scripts/gen_roundtrip_tests.py
// 43 instructions mapped out of 636 total arm32 capstone IDs.
//
//===----------------------------------------------------------------------===//

#include "SemanticRoundTripFixture.h"

TEST_P(ARM32RoundTrip, AutoLiftVerify) {
  roundTripARM32(GetParam());
}

// clang-format off

static const std::vector<RoundTripTC> kAutoARM32RoundTrip = {
  {"adc",
   "int rt_adc(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"adds %0, %1, #0\\n\\tadc %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {50, 30}, "AutoRT"},

  {"add",
   "int rt_add(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"add %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {50, 30}, "AutoRT"},

  {"and",
   "int rt_and(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"and %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {65280, 4080}, "AutoRT"},

  {"asr",
   "int rt_asr(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"asr %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {4294967040, 2}, "AutoRT"},

  {"bfc",
   "int rt_bfc(int a) {\n"
   "  __asm__ volatile (\"bfc %0, #4, #8\" : \"+r\"(a));\n"
   "  return a;\n"
   "}\n"
   "",
   {4294967295}, "AutoRT"},

  {"bfi",
   "int rt_bfi(int a, int b) {\n"
   "  __asm__ volatile (\"bfi %0, %1, #8, #8\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {4294901760, 171}, "AutoRT"},

  {"bic",
   "int rt_bic(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"bic %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {65535, 255}, "AutoRT"},

  {"clz",
   "int rt_clz(int a) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"clz %0, %1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {256}, "AutoRT"},

  {"cmn",
   "int rt_cmn(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"cmn %1, %2\\n\\tmoveq %0, #1\\n\\tmovne %0, #0\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {50, 4294967246}, "AutoRT"},

  {"eor",
   "int rt_eor(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"eor %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {255, 85}, "AutoRT"},

  {"lsl",
   "int rt_lsl(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"lsl %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {5, 3}, "AutoRT"},

  {"lsr",
   "int rt_lsr(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"lsr %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {100, 2}, "AutoRT"},

  {"mla",
   "int rt_mla(int a, int b, int c) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"mla %0, %1, %2, %3\" : \"=r\"(r) : \"r\"(a), \"r\"(b), \"r\"(c));\n"
   "  return r;\n"
   "}\n"
   "",
   {6, 7, 10}, "AutoRT"},

  {"mls",
   "int rt_mls(int a, int b, int c) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"mls %0, %1, %2, %3\" : \"=r\"(r) : \"r\"(a), \"r\"(b), \"r\"(c));\n"
   "  return r;\n"
   "}\n"
   "",
   {6, 7, 100}, "AutoRT"},

  {"mov",
   "int rt_mov(int a) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"mov %0, %1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {42}, "AutoRT"},

  {"movt",
   "int rt_movt(void) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"movw %0, #0\\n\\tmovt %0, #0x5678\" : \"=r\"(r));\n"
   "  return r;\n"
   "}\n"
   "",
   {}, "AutoRT"},

  {"movw",
   "int rt_movw(void) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"movw %0, #0x1234\" : \"=r\"(r));\n"
   "  return r;\n"
   "}\n"
   "",
   {}, "AutoRT"},

  {"mul",
   "int rt_mul(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"mul %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {6, 7}, "AutoRT"},

  {"mvn",
   "int rt_mvn(int a) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"mvn %0, %1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {255}, "AutoRT"},

  {"orr",
   "int rt_orr(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"orr %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {240, 15}, "AutoRT"},

  {"rbit",
   "int rt_rbit(int a) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"rbit %0, %1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {1}, "AutoRT"},

  {"rev",
   "int rt_rev(int a) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"rev %0, %1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {16909060}, "AutoRT"},

  {"rev16",
   "int rt_rev16(int a) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"rev16 %0, %1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {16909060}, "AutoRT"},

  {"revsh",
   "int rt_revsh(int a) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"revsh %0, %1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {258}, "AutoRT"},

  {"ror",
   "int rt_ror(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"ror %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {240, 4}, "AutoRT"},

  {"rsb",
   "int rt_rsb(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"rsb %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {30, 100}, "AutoRT"},

  {"sbc",
   "int rt_sbc(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"adds %0, %1, #0\\n\\tsbc %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {100, 30}, "AutoRT"},

  {"sbfx",
   "int rt_sbfx(int a) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"sbfx %0, %1, #4, #8\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {43981}, "AutoRT"},

  {"sdiv",
   "int rt_sdiv(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"sdiv %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {100, 7}, "AutoRT"},

  {"sub",
   "int rt_sub(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"sub %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {100, 30}, "AutoRT"},

  {"subs",
   "int rt_subs(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"subs %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {100, 30}, "AutoRT"},

  {"sxtab",
   "int rt_sxtab(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"sxtab %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {100, 128}, "AutoRT"},

  {"sxtah",
   "int rt_sxtah(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"sxtah %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {100, 32768}, "AutoRT"},

  {"sxtb",
   "int rt_sxtb(int a) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"sxtb %0, %1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {128}, "AutoRT"},

  {"sxth",
   "int rt_sxth(int a) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"sxth %0, %1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {32768}, "AutoRT"},

  {"teq",
   "int rt_teq(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"teq %1, %2\\n\\tmoveq %0, #1\\n\\tmovne %0, #0\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {42, 42}, "AutoRT"},

  {"tst",
   "int rt_tst(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"tst %1, %2\\n\\tmoveq %0, #1\\n\\tmovne %0, #0\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {255, 15}, "AutoRT"},

  {"ubfx",
   "int rt_ubfx(int a) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"ubfx %0, %1, #4, #8\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {43981}, "AutoRT"},

  {"udiv",
   "int rt_udiv(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"udiv %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {100, 7}, "AutoRT"},

  {"uxtab",
   "int rt_uxtab(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"uxtab %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {100, 171}, "AutoRT"},

  {"uxtah",
   "int rt_uxtah(int a, int b) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"uxtah %0, %1, %2\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {100, 4660}, "AutoRT"},

  {"uxtb",
   "int rt_uxtb(int a) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"uxtb %0, %1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {43981}, "AutoRT"},

  {"uxth",
   "int rt_uxth(int a) {\n"
   "  int r;\n"
   "  __asm__ volatile (\"uxth %0, %1\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {11259375}, "AutoRT"},

};

// clang-format on

INSTANTIATE_TEST_SUITE_P(AutoRT, ARM32RoundTrip,
                         ::testing::ValuesIn(kAutoARM32RoundTrip), rtTCName);
