//===- X64_AutoRoundTripTests.cpp - Auto-generated roundtrip tests --*- C++ -*-===//
//
// NeverD Decompiler
//
//===----------------------------------------------------------------------===//
//
// AUTO-GENERATED by scripts/gen_roundtrip_tests.py
// 150 instructions mapped out of 1523 total x86_64 capstone IDs.
//
//===----------------------------------------------------------------------===//

#include "SemanticRoundTripFixture.h"

TEST_P(X64RoundTrip, AutoLiftVerify) {
  roundTripX64(GetParam());
}

// clang-format off

static const std::vector<RoundTripTC> kAutoX64RoundTrip = {
  {"adc",
   "long rt_adc(long a, long b) {\n"
   "  __asm__ volatile (\"stc\\n\\tadcq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {10, 20}, "AutoRT"},

  {"adcx",
   "long rt_adcx(long a, long b) {\n"
   "  __asm__ volatile (\"clc\\n\\tadcx %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {10, 20}, "AutoRT"},

  {"add",
   "long rt_add(long a, long b) {\n"
   "  __asm__ volatile (\"addq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {100, 50}, "AutoRT"},

  {"addsd",
   "long rt_addsd(long a, long b) {\n"
   "  double af, bf;\n"
   "  __builtin_memcpy(&af, &a, 8);\n"
   "  __builtin_memcpy(&bf, &b, 8);\n"
   "  __asm__ volatile (\"addsd %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &af, 8);\n"
   "  return r;\n"
   "}\n"
   "",
   {0x4014000000000000ULL, 0x4008000000000000ULL}, "AutoRT", 0, "-msse2"},

  {"addss",
   "long rt_addss(long a, long b) {\n"
   "  float af, bf;\n"
   "  __builtin_memcpy(&af, &a, 4);\n"
   "  __builtin_memcpy(&bf, &b, 4);\n"
   "  __asm__ volatile (\"addss %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &af, 4);\n"
   "  return r;\n"
   "}\n"
   "",
   {1084227584, 1077936128}, "AutoRT", 0, "-msse"},

  {"adox",
   "long rt_adox(long a, long b) {\n"
   "  __asm__ volatile (\"clc\\n\\tadox %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {10, 20}, "AutoRT"},

  {"and",
   "long rt_and(long a, long b) {\n"
   "  __asm__ volatile (\"andq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {65280, 4080}, "AutoRT"},

  {"andn",
   "long rt_andn(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"andnq %2, %1, %0\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {255, 4660}, "AutoRT"},

  {"andnpd",
   "long rt_andnpd(long a, long b) {\n"
   "  long long af = (long long)a, bf = (long long)b;\n"
   "  __asm__ volatile (\"andnpd %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  return (long)af;\n"
   "}\n"
   "",
   {0xFFFFFFFFFFFFFFFFULL, 4294967295}, "AutoRT", 0, "-msse2"},

  {"andnps",
   "long rt_andnps(long a, long b) {\n"
   "  long long af = (long long)a, bf = (long long)b;\n"
   "  __asm__ volatile (\"andnps %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  return (long)af;\n"
   "}\n"
   "",
   {0xFFFFFFFFFFFFFFFFULL, 4294967295}, "AutoRT", 0, "-msse"},

  {"andpd",
   "long rt_andpd(long a, long b) {\n"
   "  long long af = (long long)a, bf = (long long)b;\n"
   "  __asm__ volatile (\"andpd %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  return (long)af;\n"
   "}\n"
   "",
   {0xFFFFFFFFFFFFFFFFULL, 4294967295}, "AutoRT", 0, "-msse2"},

  {"andps",
   "long rt_andps(long a, long b) {\n"
   "  long long af = (long long)a, bf = (long long)b;\n"
   "  __asm__ volatile (\"andps %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  return (long)af;\n"
   "}\n"
   "",
   {0xFFFFFFFFFFFFFFFFULL, 4294967295}, "AutoRT", 0, "-msse"},

  {"bextr",
   "long rt_bextr(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"bextrq %2, %1, %0\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {11259375, 2064}, "AutoRT"},

  {"blsi",
   "long rt_blsi(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"blsiq %1, %0\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {60}, "AutoRT"},

  {"blsmsk",
   "long rt_blsmsk(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"blsmskq %1, %0\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {60}, "AutoRT"},

  {"blsr",
   "long rt_blsr(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"blsrq %1, %0\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {60}, "AutoRT"},

  {"bsf",
   "long rt_bsf(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"bsfq %1, %0\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {128}, "AutoRT"},

  {"bsr",
   "long rt_bsr(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"bsrq %1, %0\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {128}, "AutoRT"},

  {"bswap",
   "long rt_bswap(long a) {\n"
   "  __asm__ volatile (\"bswapq %0\" : \"+r\"(a));\n"
   "  return a;\n"
   "}\n"
   "",
   {0x102030405060708ULL}, "AutoRT"},

  {"bt",
   "long rt_bt(long a) {\n"
   "  long r = 0;\n"
   "  __asm__ volatile (\"btq $3, %1\\n\\tsetc %b0\" : \"+r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {8}, "AutoRT"},

  {"btc",
   "long rt_btc(long a) {\n"
   "  __asm__ volatile (\"btcq $3, %0\" : \"+r\"(a));\n"
   "  return a;\n"
   "}\n"
   "",
   {0}, "AutoRT"},

  {"btr",
   "long rt_btr(long a) {\n"
   "  __asm__ volatile (\"btrq $3, %0\" : \"+r\"(a));\n"
   "  return a;\n"
   "}\n"
   "",
   {255}, "AutoRT"},

  {"bts",
   "long rt_bts(long a) {\n"
   "  __asm__ volatile (\"btsq $5, %0\" : \"+r\"(a));\n"
   "  return a;\n"
   "}\n"
   "",
   {0}, "AutoRT"},

  {"bzhi",
   "long rt_bzhi(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"bzhiq %2, %1, %0\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {4294967295, 16}, "AutoRT"},

  {"cmova",
   "long rt_cmova(long a, long b) {\n"
   "  __asm__ volatile (\"cmpq $50, %0\\n\\tcmovaq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {100, 42}, "AutoRT"},

  {"cmovae",
   "long rt_cmovae(long a, long b) {\n"
   "  __asm__ volatile (\"cmpq $50, %0\\n\\tcmovaeq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {100, 42}, "AutoRT"},

  {"cmovb",
   "long rt_cmovb(long a, long b) {\n"
   "  __asm__ volatile (\"cmpq $50, %0\\n\\tcmovbq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {30, 42}, "AutoRT"},

  {"cmovbe",
   "long rt_cmovbe(long a, long b) {\n"
   "  __asm__ volatile (\"cmpq $50, %0\\n\\tcmovbeq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {50, 42}, "AutoRT"},

  {"cmove",
   "long rt_cmove(long a, long b) {\n"
   "  __asm__ volatile (\"cmpq $50, %0\\n\\tcmoveq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {50, 42}, "AutoRT"},

  {"cmovg",
   "long rt_cmovg(long a, long b) {\n"
   "  __asm__ volatile (\"cmpq $50, %0\\n\\tcmovgq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {100, 42}, "AutoRT"},

  {"cmovge",
   "long rt_cmovge(long a, long b) {\n"
   "  __asm__ volatile (\"cmpq $50, %0\\n\\tcmovgeq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {100, 42}, "AutoRT"},

  {"cmovl",
   "long rt_cmovl(long a, long b) {\n"
   "  __asm__ volatile (\"cmpq $50, %0\\n\\tcmovlq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {30, 42}, "AutoRT"},

  {"cmovle",
   "long rt_cmovle(long a, long b) {\n"
   "  __asm__ volatile (\"cmpq $50, %0\\n\\tcmovleq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {50, 42}, "AutoRT"},

  {"cmovne",
   "long rt_cmovne(long a, long b) {\n"
   "  __asm__ volatile (\"cmpq $50, %0\\n\\tcmovneq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {100, 42}, "AutoRT"},

  {"cmovno",
   "long rt_cmovno(long a, long b) {\n"
   "  __asm__ volatile (\"cmpq $50, %0\\n\\tcmovnoq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {100, 42}, "AutoRT"},

  {"cmovnp",
   "long rt_cmovnp(long a, long b) {\n"
   "  __asm__ volatile (\"cmpq $50, %0\\n\\tcmovnpq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {100, 42}, "AutoRT"},

  {"cmovns",
   "long rt_cmovns(long a, long b) {\n"
   "  __asm__ volatile (\"cmpq $50, %0\\n\\tcmovnsq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {100, 42}, "AutoRT"},

  {"cmovo",
   "long rt_cmovo(long a, long b) {\n"
   "  __asm__ volatile (\"addq %1, %0\\n\\tcmovoq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {0x7FFFFFFFFFFFFFFFULL, 1}, "AutoRT"},

  {"cmovp",
   "long rt_cmovp(long a, long b) {\n"
   "  __asm__ volatile (\"cmpq $50, %0\\n\\tcmovpq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {100, 42}, "AutoRT"},

  {"cmovs",
   "long rt_cmovs(long a, long b) {\n"
   "  __asm__ volatile (\"cmpq $50, %0\\n\\tcmovsq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {100, 42}, "AutoRT"},

  {"cmp",
   "long rt_cmp(long a, long b) {\n"
   "  long r = 0;\n"
   "  __asm__ volatile (\"cmp %%rdi, %%rsi\\n\\tsete %%al\\n\\tmovzbq %%al, %%rax\"\n"
   "                   : \"=a\"(r) : \"D\"(a), \"S\"(b) : \"cc\");\n"
   "  return r;\n"
   "}\n"
   "",
   {50, 50}, "AutoRT"},

  {"comisd",
   "long rt_comisd(long a, long b) {\n"
   "  double af, bf;\n"
   "  __builtin_memcpy(&af, &a, 8);\n"
   "  __builtin_memcpy(&bf, &b, 8);\n"
   "  long r = 0;\n"
   "  __asm__ volatile (\"movsd %3, %%xmm0; comisd %%xmm0, %1\\n\\tseta %b0\"\n"
   "                   : \"+r\"(r) : \"x\"(bf), \"r\"((int)0), \"x\"(af) : \"cc\");\n"
   "  return r;\n"
   "}\n"
   "",
   {0x4014000000000000ULL, 0x4008000000000000ULL}, "AutoRT", 0, "-msse2"},

  {"comiss",
   "long rt_comiss(long a, long b) {\n"
   "  float af, bf;\n"
   "  __builtin_memcpy(&af, &a, 4);\n"
   "  __builtin_memcpy(&bf, &b, 4);\n"
   "  long r = 0;\n"
   "  __asm__ volatile (\"movss %3, %%xmm0; comiss %%xmm0, %1\\n\\tseta %b0\"\n"
   "                   : \"+r\"(r) : \"x\"(bf), \"r\"((int)0), \"x\"(af) : \"cc\");\n"
   "  return r;\n"
   "}\n"
   "",
   {1084227584, 1077936128}, "AutoRT", 0, "-msse"},

  {"cvtsd2ss",
   "long rt_cvtsd2ss(long a) {\n"
   "  double af;\n"
   "  __builtin_memcpy(&af, &a, 8);\n"
   "  float sf;\n"
   "  __asm__ volatile (\"cvtsd2ss %1, %0\" : \"=x\"(sf) : \"x\"(af));\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &sf, 4);\n"
   "  return r;\n"
   "}\n"
   "",
   {0x4014000000000000ULL}, "AutoRT", 0, "-msse2"},

  {"cvtsi2sd",
   "long rt_cvtsi2sd(long a) {\n"
   "  double df;\n"
   "  __asm__ volatile (\"cvtsi2sd %1, %0\" : \"=x\"(df) : \"r\"(a));\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &df, 8);\n"
   "  return r;\n"
   "}\n"
   "",
   {5}, "AutoRT", 0, "-msse2"},

  {"cvtsi2ss",
   "long rt_cvtsi2ss(long a) {\n"
   "  float sf;\n"
   "  __asm__ volatile (\"cvtsi2ss %1, %0\" : \"=x\"(sf) : \"r\"(a));\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &sf, 4);\n"
   "  return r;\n"
   "}\n"
   "",
   {5}, "AutoRT", 0, "-msse"},

  {"cvtss2sd",
   "long rt_cvtss2sd(long a) {\n"
   "  float af;\n"
   "  __builtin_memcpy(&af, &a, 4);\n"
   "  double df;\n"
   "  __asm__ volatile (\"cvtss2sd %1, %0\" : \"=x\"(df) : \"x\"(af));\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &df, 8);\n"
   "  return r;\n"
   "}\n"
   "",
   {1084227584}, "AutoRT", 0, "-msse2"},

  {"cvttsd2si",
   "long rt_cvttsd2si(long a) {\n"
   "  double af;\n"
   "  __builtin_memcpy(&af, &a, 8);\n"
   "  long r;\n"
   "  __asm__ volatile (\"cvttsd2si %1, %0\" : \"=r\"(r) : \"x\"(af));\n"
   "  return r;\n"
   "}\n"
   "",
   {0x4014000000000000ULL}, "AutoRT", 0, "-msse2"},

  {"cvttss2si",
   "long rt_cvttss2si(long a) {\n"
   "  float af;\n"
   "  __builtin_memcpy(&af, &a, 4);\n"
   "  long r;\n"
   "  __asm__ volatile (\"cvttss2si %1, %0\" : \"=r\"(r) : \"x\"(af));\n"
   "  return r;\n"
   "}\n"
   "",
   {1084227584}, "AutoRT", 0, "-msse"},

  {"dec",
   "long rt_dec(long a) {\n"
   "  __asm__ volatile (\"decq %0\" : \"+r\"(a));\n"
   "  return a;\n"
   "}\n"
   "",
   {100}, "AutoRT"},

  {"div",
   "long rt_div(long b) {\n"
   "  long a = 100, rdx = 0;\n"
   "  __asm__ volatile (\"xor %%rdx, %%rdx; divq %%rsi\"\n"
   "                   : \"+a\"(a) : \"S\"(b) : \"rdx\", \"cc\");\n"
   "  return a;\n"
   "}\n"
   "",
   {7}, "AutoRT"},

  {"divsd",
   "long rt_divsd(long a, long b) {\n"
   "  double af, bf;\n"
   "  __builtin_memcpy(&af, &a, 8);\n"
   "  __builtin_memcpy(&bf, &b, 8);\n"
   "  __asm__ volatile (\"divsd %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &af, 8);\n"
   "  return r;\n"
   "}\n"
   "",
   {0x4014000000000000ULL, 0x4008000000000000ULL}, "AutoRT", 0, "-msse2"},

  {"divss",
   "long rt_divss(long a, long b) {\n"
   "  float af, bf;\n"
   "  __builtin_memcpy(&af, &a, 4);\n"
   "  __builtin_memcpy(&bf, &b, 4);\n"
   "  __asm__ volatile (\"divss %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &af, 4);\n"
   "  return r;\n"
   "}\n"
   "",
   {1084227584, 1077936128}, "AutoRT", 0, "-msse"},

  {"fabs",
   "long rt_fabs(long a) {\n"
   "  double af, rf;\n"
   "  __builtin_memcpy(&af, &a, 8);\n"
   "  __asm__ volatile (\"fldl %1; fabs; fstpl %0\"\n"
   "                   : \"=m\"(rf) : \"m\"(af) : \"st\");\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &rf, 8);\n"
   "  return r;\n"
   "}\n"
   "",
   {0xC014000000000000ULL}, "AutoRT"},

  {"fadd",
   "long rt_fadd(long a, long b) {\n"
   "  double af, bf, rf;\n"
   "  __builtin_memcpy(&af, &a, 8);\n"
   "  __builtin_memcpy(&bf, &b, 8);\n"
   "  __asm__ volatile (\"fldl %1; faddl %2; fstpl %0\"\n"
   "                   : \"=m\"(rf) : \"m\"(af), \"m\"(bf) : \"st\");\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &rf, 8);\n"
   "  return r;\n"
   "}\n"
   "",
   {0x4014000000000000ULL, 0x4008000000000000ULL}, "AutoRT"},

  {"fchs",
   "long rt_fchs(long a) {\n"
   "  double af, rf;\n"
   "  __builtin_memcpy(&af, &a, 8);\n"
   "  __asm__ volatile (\"fldl %1; fchs; fstpl %0\"\n"
   "                   : \"=m\"(rf) : \"m\"(af) : \"st\");\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &rf, 8);\n"
   "  return r;\n"
   "}\n"
   "",
   {0xC014000000000000ULL}, "AutoRT"},

  {"fdiv",
   "long rt_fdiv(long a, long b) {\n"
   "  double af, bf, rf;\n"
   "  __builtin_memcpy(&af, &a, 8);\n"
   "  __builtin_memcpy(&bf, &b, 8);\n"
   "  __asm__ volatile (\"fldl %1; fdivl %2; fstpl %0\"\n"
   "                   : \"=m\"(rf) : \"m\"(af), \"m\"(bf) : \"st\");\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &rf, 8);\n"
   "  return r;\n"
   "}\n"
   "",
   {0x4014000000000000ULL, 0x4000000000000000ULL}, "AutoRT"},

  {"fmul",
   "long rt_fmul(long a, long b) {\n"
   "  double af, bf, rf;\n"
   "  __builtin_memcpy(&af, &a, 8);\n"
   "  __builtin_memcpy(&bf, &b, 8);\n"
   "  __asm__ volatile (\"fldl %1; fmull %2; fstpl %0\"\n"
   "                   : \"=m\"(rf) : \"m\"(af), \"m\"(bf) : \"st\");\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &rf, 8);\n"
   "  return r;\n"
   "}\n"
   "",
   {0x4014000000000000ULL, 0x4008000000000000ULL}, "AutoRT"},

  {"fsqrt",
   "long rt_fsqrt(long a) {\n"
   "  double af, rf;\n"
   "  __builtin_memcpy(&af, &a, 8);\n"
   "  __asm__ volatile (\"fldl %1; fsqrt; fstpl %0\"\n"
   "                   : \"=m\"(rf) : \"m\"(af) : \"st\");\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &rf, 8);\n"
   "  return r;\n"
   "}\n"
   "",
   {0x4014000000000000ULL}, "AutoRT"},

  {"fsub",
   "long rt_fsub(long a, long b) {\n"
   "  double af, bf, rf;\n"
   "  __builtin_memcpy(&af, &a, 8);\n"
   "  __builtin_memcpy(&bf, &b, 8);\n"
   "  __asm__ volatile (\"fldl %1; fsubl %2; fstpl %0\"\n"
   "                   : \"=m\"(rf) : \"m\"(af), \"m\"(bf) : \"st\");\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &rf, 8);\n"
   "  return r;\n"
   "}\n"
   "",
   {0x4014000000000000ULL, 0x4008000000000000ULL}, "AutoRT"},

  {"idiv",
   "long rt_idiv(long b) {\n"
   "  long a = 100, rdx = 0;\n"
   "  __asm__ volatile (\"cqo; idivq %%rsi\"\n"
   "                   : \"+a\"(a) : \"S\"(b) : \"rdx\", \"cc\");\n"
   "  return a;\n"
   "}\n"
   "",
   {7}, "AutoRT"},

  {"imul",
   "long rt_imul(long a, long b) {\n"
   "  __asm__ volatile (\"imulq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {6, 7}, "AutoRT"},

  {"inc",
   "long rt_inc(long a) {\n"
   "  __asm__ volatile (\"incq %0\" : \"+r\"(a));\n"
   "  return a;\n"
   "}\n"
   "",
   {99}, "AutoRT"},

  {"lea",
   "long rt_lea(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"lea (%1,%2,4), %%rax\" : \"=a\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {100, 10}, "AutoRT"},

  {"lzcnt",
   "long rt_lzcnt(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"lzcntq %1, %0\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {128}, "AutoRT"},

  {"maxsd",
   "long rt_maxsd(long a, long b) {\n"
   "  double af, bf;\n"
   "  __builtin_memcpy(&af, &a, 8);\n"
   "  __builtin_memcpy(&bf, &b, 8);\n"
   "  __asm__ volatile (\"maxsd %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &af, 8);\n"
   "  return r;\n"
   "}\n"
   "",
   {0x4014000000000000ULL, 0x4008000000000000ULL}, "AutoRT", 0, "-msse2"},

  {"maxss",
   "long rt_maxss(long a, long b) {\n"
   "  float af, bf;\n"
   "  __builtin_memcpy(&af, &a, 4);\n"
   "  __builtin_memcpy(&bf, &b, 4);\n"
   "  __asm__ volatile (\"maxss %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &af, 4);\n"
   "  return r;\n"
   "}\n"
   "",
   {1084227584, 1077936128}, "AutoRT", 0, "-msse"},

  {"minsd",
   "long rt_minsd(long a, long b) {\n"
   "  double af, bf;\n"
   "  __builtin_memcpy(&af, &a, 8);\n"
   "  __builtin_memcpy(&bf, &b, 8);\n"
   "  __asm__ volatile (\"minsd %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &af, 8);\n"
   "  return r;\n"
   "}\n"
   "",
   {0x4014000000000000ULL, 0x4008000000000000ULL}, "AutoRT", 0, "-msse2"},

  {"minss",
   "long rt_minss(long a, long b) {\n"
   "  float af, bf;\n"
   "  __builtin_memcpy(&af, &a, 4);\n"
   "  __builtin_memcpy(&bf, &b, 4);\n"
   "  __asm__ volatile (\"minss %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &af, 4);\n"
   "  return r;\n"
   "}\n"
   "",
   {1084227584, 1077936128}, "AutoRT", 0, "-msse"},

  {"mov",
   "long rt_mov(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"movq %1, %0\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {42}, "AutoRT"},

  {"movabs",
   "long rt_movabs(void) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"movabsq $0x1234567890ABCDEF, %0\" : \"=r\"(r));\n"
   "  return r;\n"
   "}\n"
   "",
   {}, "AutoRT"},

  {"movaps",
   "long rt_movaps(long a, long b) {\n"
   "  long long bf = (long long)b, out;\n"
   "  __asm__ volatile (\"movaps %0, %1\" : \"=x\"(out) : \"x\"(bf));\n"
   "  return (long)out;\n"
   "}\n"
   "",
   {0x200000001ULL, 0x400000003ULL}, "AutoRT", 0, "-msse"},

  {"movsd",
   "long rt_movsd(long a, long b) {\n"
   "  double af, bf;\n"
   "  __builtin_memcpy(&af, &a, 8);\n"
   "  __builtin_memcpy(&bf, &b, 8);\n"
   "  __asm__ volatile (\"movsd %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &af, 8);\n"
   "  return r;\n"
   "}\n"
   "",
   {0x4014000000000000ULL, 0x4008000000000000ULL}, "AutoRT", 0, "-msse2"},

  {"movss",
   "long rt_movss(long a, long b) {\n"
   "  float af, bf;\n"
   "  __builtin_memcpy(&af, &a, 4);\n"
   "  __builtin_memcpy(&bf, &b, 4);\n"
   "  __asm__ volatile (\"movss %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &af, 4);\n"
   "  return r;\n"
   "}\n"
   "",
   {1084227584, 1077936128}, "AutoRT", 0, "-msse"},

  {"movsx",
   "long rt_movsx(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"movsbl %b1, %k0\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {128}, "AutoRT"},

  {"movsxd",
   "long rt_movsxd(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"movslq %k1, %0\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {4294967295}, "AutoRT"},

  {"movups",
   "long rt_movups(long a, long b) {\n"
   "  long long bf = (long long)b, out;\n"
   "  __asm__ volatile (\"movups %0, %1\" : \"=x\"(out) : \"x\"(bf));\n"
   "  return (long)out;\n"
   "}\n"
   "",
   {0x200000001ULL, 0x400000003ULL}, "AutoRT", 0, "-msse"},

  {"movzx",
   "long rt_movzx(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"movzbl %b1, %k0\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {65346}, "AutoRT"},

  {"mul",
   "long rt_mul(long a, long b) {\n"
   "  __asm__ volatile (\"mulq %%rsi\" : \"+a\"(a) : \"S\"(b) : \"cc\");\n"
   "  return a;\n"
   "}\n"
   "",
   {6, 7}, "AutoRT"},

  {"mulsd",
   "long rt_mulsd(long a, long b) {\n"
   "  double af, bf;\n"
   "  __builtin_memcpy(&af, &a, 8);\n"
   "  __builtin_memcpy(&bf, &b, 8);\n"
   "  __asm__ volatile (\"mulsd %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &af, 8);\n"
   "  return r;\n"
   "}\n"
   "",
   {0x4014000000000000ULL, 0x4008000000000000ULL}, "AutoRT", 0, "-msse2"},

  {"mulss",
   "long rt_mulss(long a, long b) {\n"
   "  float af, bf;\n"
   "  __builtin_memcpy(&af, &a, 4);\n"
   "  __builtin_memcpy(&bf, &b, 4);\n"
   "  __asm__ volatile (\"mulss %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &af, 4);\n"
   "  return r;\n"
   "}\n"
   "",
   {1084227584, 1077936128}, "AutoRT", 0, "-msse"},

  {"mulx",
   "long rt_mulx(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"mulxq %2, %0, %1\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {6, 7}, "AutoRT"},

  {"neg",
   "long rt_neg(long a) {\n"
   "  __asm__ volatile (\"negq %0\" : \"+r\"(a));\n"
   "  return a;\n"
   "}\n"
   "",
   {42}, "AutoRT"},

  {"not",
   "long rt_not(long a) {\n"
   "  __asm__ volatile (\"notq %0\" : \"+r\"(a));\n"
   "  return a;\n"
   "}\n"
   "",
   {255}, "AutoRT"},

  {"or",
   "long rt_or(long a, long b) {\n"
   "  __asm__ volatile (\"orq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {240, 15}, "AutoRT"},

  {"orpd",
   "long rt_orpd(long a, long b) {\n"
   "  long long af = (long long)a, bf = (long long)b;\n"
   "  __asm__ volatile (\"orpd %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  return (long)af;\n"
   "}\n"
   "",
   {4294967295, 0xFFFFFFFF00000000ULL}, "AutoRT", 0, "-msse2"},

  {"orps",
   "long rt_orps(long a, long b) {\n"
   "  long long af = (long long)a, bf = (long long)b;\n"
   "  __asm__ volatile (\"orps %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  return (long)af;\n"
   "}\n"
   "",
   {4294967295, 0xFFFFFFFF00000000ULL}, "AutoRT", 0, "-msse"},

  {"pabsd",
   "long rt_pabsd(long a) {\n"
   "  long long af = (long long)a, out;\n"
   "  __asm__ volatile (\"pabsd %1, %0\" : \"=x\"(out) : \"x\"(af));\n"
   "  return (long)out;\n"
   "}\n"
   "",
   {0xFFFFFFF800000004ULL}, "AutoRT", 0, "-mssse3"},

  {"paddd",
   "long rt_paddd(long a, long b) {\n"
   "  long long af = (long long)a, bf = (long long)b;\n"
   "  __asm__ volatile (\"paddd %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  return (long)af;\n"
   "}\n"
   "",
   {0x200000001ULL, 0x400000003ULL}, "AutoRT", 0, "-msse2"},

  {"pand",
   "long rt_pand(long a, long b) {\n"
   "  long long af = (long long)a, bf = (long long)b;\n"
   "  __asm__ volatile (\"pand %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  return (long)af;\n"
   "}\n"
   "",
   {0xFFFFFFFFFFFFFFFFULL, 4294967295}, "AutoRT", 0, "-msse2"},

  {"pandn",
   "long rt_pandn(long a, long b) {\n"
   "  long long af = (long long)a, bf = (long long)b;\n"
   "  __asm__ volatile (\"pandn %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  return (long)af;\n"
   "}\n"
   "",
   {0xFFFFFFFFFFFFFFFFULL, 4294967295}, "AutoRT", 0, "-msse2"},

  {"pcmpeqd",
   "long rt_pcmpeqd(long a, long b) {\n"
   "  long long af = (long long)a, bf = (long long)b;\n"
   "  __asm__ volatile (\"pcmpeqd %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  return (long)af;\n"
   "}\n"
   "",
   {0x200000001ULL, 0x200000001ULL}, "AutoRT", 0, "-msse2"},

  {"pdep",
   "long rt_pdep(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"pdepq %2, %1, %0\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {305419896, 255}, "AutoRT"},

  {"pext",
   "long rt_pext(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"pextq %2, %1, %0\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {305419896, 255}, "AutoRT"},

  {"pmaxud",
   "long rt_pmaxud(long a, long b) {\n"
   "  long long af = (long long)a, bf = (long long)b;\n"
   "  __asm__ volatile (\"pmaxud %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  return (long)af;\n"
   "}\n"
   "",
   {0x600000005ULL, 0x400000003ULL}, "AutoRT", 0, "-msse4.1"},

  {"pminud",
   "long rt_pminud(long a, long b) {\n"
   "  long long af = (long long)a, bf = (long long)b;\n"
   "  __asm__ volatile (\"pminud %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  return (long)af;\n"
   "}\n"
   "",
   {0x600000005ULL, 0x400000003ULL}, "AutoRT", 0, "-msse4.1"},

  {"popcnt",
   "long rt_popcnt(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"popcntq %1, %0\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {255}, "AutoRT"},

  {"por",
   "long rt_por(long a, long b) {\n"
   "  long long af = (long long)a, bf = (long long)b;\n"
   "  __asm__ volatile (\"por %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  return (long)af;\n"
   "}\n"
   "",
   {4294967295, 0xFFFFFFFF00000000ULL}, "AutoRT", 0, "-msse2"},

  {"pslld",
   "long rt_pslld(long a) {\n"
   "  long long af = (long long)a;\n"
   "  __asm__ volatile (\"pslld $2, %0\" : \"+x\"(af));\n"
   "  return (long)af;\n"
   "}\n"
   "",
   {0x200000001ULL}, "AutoRT", 0, "-msse2"},

  {"psrad",
   "long rt_psrad(long a) {\n"
   "  long long af = (long long)a;\n"
   "  __asm__ volatile (\"psrad $1, %0\" : \"+x\"(af));\n"
   "  return (long)af;\n"
   "}\n"
   "",
   {0xFFFFFFF800000004ULL}, "AutoRT", 0, "-msse2"},

  {"psrld",
   "long rt_psrld(long a) {\n"
   "  long long af = (long long)a;\n"
   "  __asm__ volatile (\"psrld $1, %0\" : \"+x\"(af));\n"
   "  return (long)af;\n"
   "}\n"
   "",
   {0x600000004ULL}, "AutoRT", 0, "-msse2"},

  {"psubd",
   "long rt_psubd(long a, long b) {\n"
   "  long long af = (long long)a, bf = (long long)b;\n"
   "  __asm__ volatile (\"psubd %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  return (long)af;\n"
   "}\n"
   "",
   {0x600000005ULL, 0x200000001ULL}, "AutoRT", 0, "-msse2"},

  {"push",
   "long rt_push(long a) {\n"
   "  __asm__ volatile (\"pushq %0\\n\\tpopq %0\" : \"+r\"(a));\n"
   "  return a;\n"
   "}\n"
   "",
   {42}, "AutoRT"},

  {"pxor",
   "long rt_pxor(long a, long b) {\n"
   "  long long af = (long long)a, bf = (long long)b;\n"
   "  __asm__ volatile (\"pxor %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  return (long)af;\n"
   "}\n"
   "",
   {0xFFFFFFFFFFFFFFFFULL, 4294967295}, "AutoRT", 0, "-msse2"},

  {"rcl",
   "long rt_rcl(long a) {\n"
   "  __asm__ volatile (\"clc\\n\\trclq $1, %0\" : \"+r\"(a));\n"
   "  return a;\n"
   "}\n"
   "",
   {15}, "AutoRT"},

  {"rcpss",
   "long rt_rcpss(long a) {\n"
   "  float af;\n"
   "  __builtin_memcpy(&af, &a, 4);\n"
   "  __asm__ volatile (\"rcpss %1, %0\" : \"+x\"(af));\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &af, 4);\n"
   "  return r;\n"
   "}\n"
   "",
   {1084227584}, "AutoRT", 0, "-msse"},

  {"rcr",
   "long rt_rcr(long a) {\n"
   "  __asm__ volatile (\"clc\\n\\trcrq $1, %0\" : \"+r\"(a));\n"
   "  return a;\n"
   "}\n"
   "",
   {240}, "AutoRT"},

  {"rol",
   "long rt_rol(long a) {\n"
   "  __asm__ volatile (\"rolq $4, %0\" : \"+r\"(a));\n"
   "  return a;\n"
   "}\n"
   "",
   {15}, "AutoRT"},

  {"ror",
   "long rt_ror(long a) {\n"
   "  __asm__ volatile (\"rorq $4, %0\" : \"+r\"(a));\n"
   "  return a;\n"
   "}\n"
   "",
   {240}, "AutoRT"},

  {"rorx",
   "long rt_rorx(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"rorxq $4, %1, %0\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {240}, "AutoRT"},

  {"rsqrtss",
   "long rt_rsqrtss(long a) {\n"
   "  float af;\n"
   "  __builtin_memcpy(&af, &a, 4);\n"
   "  __asm__ volatile (\"rsqrtss %1, %0\" : \"+x\"(af));\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &af, 4);\n"
   "  return r;\n"
   "}\n"
   "",
   {1084227584}, "AutoRT", 0, "-msse"},

  {"sal",
   "long rt_sal(long a) {\n"
   "  __asm__ volatile (\"salq $3, %0\" : \"+r\"(a));\n"
   "  return a;\n"
   "}\n"
   "",
   {5}, "AutoRT"},

  {"sar",
   "long rt_sar(long a) {\n"
   "  __asm__ volatile (\"sarq $2, %0\" : \"+r\"(a));\n"
   "  return a;\n"
   "}\n"
   "",
   {0xFFFFFFFFFFFFFF00ULL}, "AutoRT"},

  {"sarx",
   "long rt_sarx(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"sarxq %2, %1, %0\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {0xFFFFFFFF80000000ULL, 4}, "AutoRT"},

  {"sbb",
   "long rt_sbb(long a, long b) {\n"
   "  __asm__ volatile (\"stc\\n\\tsbbq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {100, 30}, "AutoRT"},

  {"seta",
   "long rt_seta(long a) {\n"
   "  long r = 0;\n"
   "  __asm__ volatile (\"cmpq $50, %1\\n\\tseta %b0\" : \"+r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {100}, "AutoRT"},

  {"setae",
   "long rt_setae(long a) {\n"
   "  long r = 0;\n"
   "  __asm__ volatile (\"cmpq $50, %1\\n\\tsetae %b0\" : \"+r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {100}, "AutoRT"},

  {"setb",
   "long rt_setb(long a) {\n"
   "  long r = 0;\n"
   "  __asm__ volatile (\"cmpq $50, %1\\n\\tsetb %b0\" : \"+r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {30}, "AutoRT"},

  {"setbe",
   "long rt_setbe(long a) {\n"
   "  long r = 0;\n"
   "  __asm__ volatile (\"cmpq $50, %1\\n\\tsetbe %b0\" : \"+r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {50}, "AutoRT"},

  {"sete",
   "long rt_sete(long a) {\n"
   "  long r = 0;\n"
   "  __asm__ volatile (\"cmpq $50, %1\\n\\tsete %b0\" : \"+r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {50}, "AutoRT"},

  {"setg",
   "long rt_setg(long a) {\n"
   "  long r = 0;\n"
   "  __asm__ volatile (\"cmpq $50, %1\\n\\tsetg %b0\" : \"+r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {100}, "AutoRT"},

  {"setge",
   "long rt_setge(long a) {\n"
   "  long r = 0;\n"
   "  __asm__ volatile (\"cmpq $50, %1\\n\\tsetge %b0\" : \"+r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {50}, "AutoRT"},

  {"setl",
   "long rt_setl(long a) {\n"
   "  long r = 0;\n"
   "  __asm__ volatile (\"cmpq $50, %1\\n\\tsetl %b0\" : \"+r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {30}, "AutoRT"},

  {"setle",
   "long rt_setle(long a) {\n"
   "  long r = 0;\n"
   "  __asm__ volatile (\"cmpq $50, %1\\n\\tsetle %b0\" : \"+r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {50}, "AutoRT"},

  {"setne",
   "long rt_setne(long a) {\n"
   "  long r = 0;\n"
   "  __asm__ volatile (\"cmpq $50, %1\\n\\tsetne %b0\" : \"+r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {100}, "AutoRT"},

  {"setno",
   "long rt_setno(long a) {\n"
   "  long r = 0;\n"
   "  __asm__ volatile (\"cmpq $50, %1\\n\\tsetno %b0\" : \"+r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {100}, "AutoRT"},

  {"setnp",
   "long rt_setnp(long a) {\n"
   "  long r = 0;\n"
   "  __asm__ volatile (\"cmpq $50, %1\\n\\tsetnp %b0\" : \"+r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {100}, "AutoRT"},

  {"setns",
   "long rt_setns(long a) {\n"
   "  long r = 0;\n"
   "  __asm__ volatile (\"cmpq $50, %1\\n\\tsetns %b0\" : \"+r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {100}, "AutoRT"},

  {"setp",
   "long rt_setp(long a) {\n"
   "  long r = 0;\n"
   "  __asm__ volatile (\"cmpq $50, %1\\n\\tsetp %b0\" : \"+r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {100}, "AutoRT"},

  {"sets",
   "long rt_sets(long a) {\n"
   "  long r = 0;\n"
   "  __asm__ volatile (\"cmpq $50, %1\\n\\tsets %b0\" : \"+r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {100}, "AutoRT"},

  {"shl",
   "long rt_shl(long a) {\n"
   "  __asm__ volatile (\"shlq $3, %0\" : \"+r\"(a));\n"
   "  return a;\n"
   "}\n"
   "",
   {5}, "AutoRT"},

  {"shld",
   "long rt_shld(long a, long b) {\n"
   "  __asm__ volatile (\"shldq $4, %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {240, 15}, "AutoRT"},

  {"shlx",
   "long rt_shlx(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"shlxq %2, %1, %0\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {1, 10}, "AutoRT"},

  {"shr",
   "long rt_shr(long a) {\n"
   "  __asm__ volatile (\"shrq $2, %0\" : \"+r\"(a));\n"
   "  return a;\n"
   "}\n"
   "",
   {100}, "AutoRT"},

  {"shrd",
   "long rt_shrd(long a, long b) {\n"
   "  __asm__ volatile (\"shrdq $4, %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {240, 0xF00000000000000ULL}, "AutoRT"},

  {"shrx",
   "long rt_shrx(long a, long b) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"shrxq %2, %1, %0\" : \"=r\"(r) : \"r\"(a), \"r\"(b));\n"
   "  return r;\n"
   "}\n"
   "",
   {256, 2}, "AutoRT"},

  {"sqrtsd",
   "long rt_sqrtsd(long a) {\n"
   "  double af;\n"
   "  __builtin_memcpy(&af, &a, 8);\n"
   "  __asm__ volatile (\"sqrtsd %1, %0\" : \"+x\"(af));\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &af, 8);\n"
   "  return r;\n"
   "}\n"
   "",
   {0x4014000000000000ULL}, "AutoRT", 0, "-msse2"},

  {"sqrtss",
   "long rt_sqrtss(long a) {\n"
   "  float af;\n"
   "  __builtin_memcpy(&af, &a, 4);\n"
   "  __asm__ volatile (\"sqrtss %1, %0\" : \"+x\"(af));\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &af, 4);\n"
   "  return r;\n"
   "}\n"
   "",
   {1084227584}, "AutoRT", 0, "-msse"},

  {"sub",
   "long rt_sub(long a, long b) {\n"
   "  __asm__ volatile (\"subq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {100, 30}, "AutoRT"},

  {"subsd",
   "long rt_subsd(long a, long b) {\n"
   "  double af, bf;\n"
   "  __builtin_memcpy(&af, &a, 8);\n"
   "  __builtin_memcpy(&bf, &b, 8);\n"
   "  __asm__ volatile (\"subsd %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &af, 8);\n"
   "  return r;\n"
   "}\n"
   "",
   {0x4014000000000000ULL, 0x4008000000000000ULL}, "AutoRT", 0, "-msse2"},

  {"subss",
   "long rt_subss(long a, long b) {\n"
   "  float af, bf;\n"
   "  __builtin_memcpy(&af, &a, 4);\n"
   "  __builtin_memcpy(&bf, &b, 4);\n"
   "  __asm__ volatile (\"subss %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  long r;\n"
   "  __builtin_memcpy(&r, &af, 4);\n"
   "  return r;\n"
   "}\n"
   "",
   {1084227584, 1077936128}, "AutoRT", 0, "-msse"},

  {"test",
   "long rt_test(long a) {\n"
   "  long r = 0;\n"
   "  __asm__ volatile (\"testq %0, %1\\n\\tsete %b0\" : \"+r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {255}, "AutoRT"},

  {"tzcnt",
   "long rt_tzcnt(long a) {\n"
   "  long r;\n"
   "  __asm__ volatile (\"tzcntq %1, %0\" : \"=r\"(r) : \"r\"(a));\n"
   "  return r;\n"
   "}\n"
   "",
   {128}, "AutoRT"},

  {"ucomisd",
   "long rt_ucomisd(long a, long b) {\n"
   "  double af, bf;\n"
   "  __builtin_memcpy(&af, &a, 8);\n"
   "  __builtin_memcpy(&bf, &b, 8);\n"
   "  long r = 0;\n"
   "  __asm__ volatile (\"movsd %3, %%xmm0; ucomisd %%xmm0, %1\\n\\tsete %b0\"\n"
   "                   : \"+r\"(r) : \"x\"(bf), \"r\"((int)0), \"x\"(af) : \"cc\");\n"
   "  return r;\n"
   "}\n"
   "",
   {0x4014000000000000ULL, 0x4014000000000000ULL}, "AutoRT", 0, "-msse2"},

  {"ucomiss",
   "long rt_ucomiss(long a, long b) {\n"
   "  float af, bf;\n"
   "  __builtin_memcpy(&af, &a, 4);\n"
   "  __builtin_memcpy(&bf, &b, 4);\n"
   "  long r = 0;\n"
   "  __asm__ volatile (\"movss %3, %%xmm0; ucomiss %%xmm0, %1\\n\\tsete %b0\"\n"
   "                   : \"+r\"(r) : \"x\"(bf), \"r\"((int)0), \"x\"(af) : \"cc\");\n"
   "  return r;\n"
   "}\n"
   "",
   {1084227584, 1084227584}, "AutoRT", 0, "-msse"},

  {"xadd",
   "long rt_xadd(long a, long b) {\n"
   "  __asm__ volatile (\"xaddq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {10, 20}, "AutoRT"},

  {"xchg",
   "long rt_xchg(long a, long b) {\n"
   "  __asm__ volatile (\"xchgq %0, %1\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {1, 2}, "AutoRT"},

  {"xor",
   "long rt_xor(long a, long b) {\n"
   "  __asm__ volatile (\"xorq %1, %0\" : \"+r\"(a) : \"r\"(b));\n"
   "  return a;\n"
   "}\n"
   "",
   {255, 85}, "AutoRT"},

  {"xorpd",
   "long rt_xorpd(long a, long b) {\n"
   "  long long af = (long long)a, bf = (long long)b;\n"
   "  __asm__ volatile (\"xorpd %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  return (long)af;\n"
   "}\n"
   "",
   {0xFFFFFFFFFFFFFFFFULL, 4294967295}, "AutoRT", 0, "-msse2"},

  {"xorps",
   "long rt_xorps(long a, long b) {\n"
   "  long long af = (long long)a, bf = (long long)b;\n"
   "  __asm__ volatile (\"xorps %1, %0\" : \"+x\"(af) : \"x\"(bf));\n"
   "  return (long)af;\n"
   "}\n"
   "",
   {0xFFFFFFFFFFFFFFFFULL, 4294967295}, "AutoRT", 0, "-msse"},

};

// clang-format on

INSTANTIATE_TEST_SUITE_P(AutoRT, X64RoundTrip,
                         ::testing::ValuesIn(kAutoX64RoundTrip), rtTCName);
