//===- X64_AVX2ReduceRTTests.cpp - AVX2 (VEX.128 + VEX.256) reductions --*-C++*-=//
//
// NeverD Decompiler
//
//===----------------------------------------------------------------------===//
//
// x86_64-only probes compiled with -O3 -mavx2 to reach AVX2 reduction idioms
// generated by loop auto-vectorization that the explicit-intrinsic AVX tests do
// not cover.  Both VEX.128 and VEX.256 (YMM) shapes are exercised: the unicorn
// fork now executes 256-bit YMM encodings lane-wise (qemu/target/i386
// gen_sse_256), so the widening / abs-max reductions clang lowers to YMM verify
// natively here — see the Unicorn unsupported-instructions doc (#432).
//
//   * maddw  - sum of i16*i16 products: clang emits VPMADDWD (VEX.128).
//   * sadbw  - sum of |a-b| over bytes: clang emits VPSADBW (VEX.128).
//   * gather - sum of table[idx[i]] with a runtime index array: VEX.128
//              VPGATHERDD (or a scalar indexed reload fallback).
//   * wmuldq - u32*u32->u64 widening reduction: VPMOVZXDQ/VPMULUDQ/VPADDQ ymm
//              with a VEXTRACTI128 fold tail.
//   * maxabs - max |i32| reduction: VPABSD/VPMAXUD ymm with a VEXTRACTI128 fold.
//
// Each kernel folds to a single integer return, checked native vs lifted.
//
//===----------------------------------------------------------------------===//

#include "SemanticRoundTripFixture.h"

class X64AVX2ReduceRT : public SemanticRoundTripFixture,
                        public ::testing::WithParamInterface<RoundTripTC> {};
TEST_P(X64AVX2ReduceRT, Verify) { roundTripX64(GetParam()); }

// clang-format off
static std::vector<RoundTripTC> makeAVX2ReduceTC() {
  std::string p = "x64av2";
  return {
    // i16*i16 product reduction -> VPMADDWD.
    {p+"_maddw",
     "long "+p+"_maddw(long a){\n"
     "  short u[64],v[64]; unsigned x=(unsigned)a|1u;\n"
     "  for(int i=0;i<64;i++){ x=x*1103515245u+12345u; u[i]=(short)(x>>11);\n"
     "    x=x*1103515245u+12345u; v[i]=(short)(x>>11); }\n"
     "  int s=0; for(int i=0;i<64;i++) s+=(int)u[i]*(int)v[i];\n"
     "  return (long)(unsigned)s; }\n",
     {0x4cULL}, "AVX2Reduce", 3, "-mavx2"},

    // byte sum of absolute differences -> VPSADBW.
    {p+"_sadbw",
     "long "+p+"_sadbw(long a){\n"
     "  unsigned char u[128],v[128]; unsigned x=(unsigned)a|1u;\n"
     "  for(int i=0;i<128;i++){ x=x*1103515245u+12345u; u[i]=(unsigned char)(x>>13);\n"
     "    x=x*1103515245u+12345u; v[i]=(unsigned char)(x>>13); }\n"
     "  unsigned s=0; for(int i=0;i<128;i++){ int d=(int)u[i]-(int)v[i]; s+=(unsigned)(d<0?-d:d); }\n"
     "  return (long)(unsigned)s; }\n",
     {0x9bULL}, "AVX2Reduce", 3, "-mavx2"},

    // indexed gather load reduction -> VPGATHERDD (or scalar fallback).
    {p+"_gather",
     "long "+p+"_gather(long a){\n"
     "  unsigned tab[64]; unsigned idx[64]; unsigned x=(unsigned)a|1u;\n"
     "  for(int i=0;i<64;i++){ x=x*1103515245u+12345u; tab[i]=x; }\n"
     "  for(int i=0;i<64;i++){ x=x*1103515245u+12345u; idx[i]=(x>>5)&63u; }\n"
     "  unsigned s=0; for(int i=0;i<64;i++) s+=tab[idx[i]];\n"
     "  return (long)(unsigned)s; }\n",
     {0x35ULL}, "AVX2Reduce", 3, "-mavx2"},

    // u32*u32->u64 widening reduction -> VPMOVZXDQ + VPMULUDQ + VPADDQ (ymm),
    // VEXTRACTI128 fold tail.
    {p+"_wmuldq",
     "long "+p+"_wmuldq(long a){\n"
     "  unsigned u[64]; unsigned x=(unsigned)a|1u;\n"
     "  for(int i=0;i<64;i++){ x=x*1103515245u+12345u; u[i]=x; }\n"
     "  unsigned long s=0; for(int i=0;i<64;i++) s+=(unsigned long)u[i]*(unsigned long)u[i];\n"
     "  return (long)s; }\n",
     {0x4cULL}, "AVX2Reduce", 3, "-mavx2"},

    // max |i32| reduction -> VPABSD + VPMAXUD (ymm), VEXTRACTI128 fold tail.
    {p+"_maxabs",
     "long "+p+"_maxabs(long a){\n"
     "  int v[64]; unsigned x=(unsigned)a|1u;\n"
     "  for(int i=0;i<64;i++){ x=x*1103515245u+12345u; v[i]=(int)x; }\n"
     "  unsigned best=0;\n"
     "  for(int i=0;i<64;i++){ int t=v[i]; unsigned u=t<0?(unsigned)(-t):(unsigned)t; if(u>best)best=u; }\n"
     "  return (long)best; }\n",
     {0x77ULL}, "AVX2Reduce", 3, "-mavx2"},
  };
}
// clang-format on

static const std::vector<RoundTripTC> kAVX2 = makeAVX2ReduceTC();
INSTANTIATE_TEST_SUITE_P(AVX2Reduce, X64AVX2ReduceRT, ::testing::ValuesIn(kAVX2), rtTCName);
