# These native/C differential cases repeatedly invoke external compilers.
# Keep the normal per-case deadline and full matrix, without competing CTest
# compilation workloads. Apply after PRE_TEST GoogleTest discovery.
foreach(_neverd_fp_state_test IN LISTS NeverDX86FPStateAccuracyTests_TESTS)
  if(_neverd_fp_state_test MATCHES "^X86FPStateAccuracy\\.")
    set_tests_properties("${_neverd_fp_state_test}" PROPERTIES RUN_SERIAL TRUE)
  endif()
endforeach()
foreach(_neverd_fp_state_test IN LISTS NeverDX86FPConversionAccuracyTests_TESTS)
  if(_neverd_fp_state_test MATCHES "^X86FPConversionExecution\\.")
    set_tests_properties("${_neverd_fp_state_test}" PROPERTIES RUN_SERIAL TRUE)
  endif()
endforeach()
unset(_neverd_fp_state_test)
foreach(_neverd_fp_round_test IN LISTS NeverDX86FPRoundAccuracyTests_TESTS)
  if(_neverd_fp_round_test MATCHES "^X86FPRoundAccuracy\\.")
    set_tests_properties("${_neverd_fp_round_test}" PROPERTIES RUN_SERIAL TRUE)
  endif()
endforeach()
unset(_neverd_fp_round_test)
foreach(_neverd_fp_approx_test IN LISTS NeverDX86FPApprox12AccuracyTests_TESTS)
  if(_neverd_fp_approx_test MATCHES "^X86FPApprox12Accuracy\\.")
    set_tests_properties("${_neverd_fp_approx_test}" PROPERTIES RUN_SERIAL TRUE)
  endif()
endforeach()
unset(_neverd_fp_approx_test)
