#ifndef NEVERD_LIBC_LIBCMATH_H
#define NEVERD_LIBC_LIBCMATH_H

#include "neverd/libc/LibCNames.h"

#include <array>
#include <string_view>

namespace neverd::libc {

/// ISO C math.h — transcendental and arithmetic (double / float / long double)
inline constexpr std::string_view kMathHeader = "math.h";

inline constexpr std::array kMathFunctions = {
    // double
    "acos",
    "acosh",
    "asin",
    "asinh",
    "atan",
    "atan2",
    "atanh",
    "cbrt",
    "ceil",
    "copysign",
    "cos",
    "cosh",
    "erf",
    "erfc",
    "exp",
    "exp2",
    "expm1",
    "fabs",
    "fdim",
    "floor",
    "fma",
    "fmax",
    "fmin",
    "fmod",
    "frexp",
    "hypot",
    "ilogb",
    "ldexp",
    "lgamma",
    "llrint",
    "llround",
    "log",
    "log10",
    "log1p",
    "log2",
    "logb",
    "lrint",
    "lround",
    "modf",
    "nan",
    "nearbyint",
    "nextafter",
    "nexttoward",
    "pow",
    "remainder",
    "remquo",
    "rint",
    "round",
    "scalbln",
    "scalbn",
    "sin",
    "sinh",
    "sqrt",
    "tan",
    "tanh",
    "tgamma",
    "trunc",
    // float (f suffix)
    "acosf",
    "acoshf",
    "asinf",
    "asinhf",
    "atanf",
    "atan2f",
    "atanhf",
    "cbrtf",
    "ceilf",
    "copysignf",
    "cosf",
    "coshf",
    "erff",
    "erfcf",
    "expf",
    "exp2f",
    "expm1f",
    "fabsf",
    "fdimf",
    "floorf",
    "fmaf",
    "fmaxf",
    "fminf",
    "fmodf",
    "frexpf",
    "hypotf",
    "ilogbf",
    "ldexpf",
    "lgammaf",
    "llrintf",
    "llroundf",
    "logf",
    "log10f",
    "log1pf",
    "log2f",
    "logbf",
    "lrintf",
    "lroundf",
    "modff",
    "nanf",
    "nearbyintf",
    "nextafterf",
    "nexttowardf",
    "powf",
    "remainderf",
    "remquof",
    "rintf",
    "roundf",
    "scalblnf",
    "scalbnf",
    "sinf",
    "sinhf",
    "sqrtf",
    "tanf",
    "tanhf",
    "tgammaf",
    "truncf",
    // long double (l suffix)
    "acosl",
    "acoshl",
    "asinl",
    "asinhl",
    "atanl",
    "atan2l",
    "atanhl",
    "cbrtl",
    "ceill",
    "copysignl",
    "cosl",
    "coshl",
    "erfl",
    "erfcl",
    "expl",
    "exp2l",
    "expm1l",
    "fabsl",
    "fdiml",
    "floorl",
    "fmal",
    "fmaxl",
    "fminl",
    "fmodl",
    "frexpl",
    "hypotl",
    "ilogbl",
    "ldexpl",
    "lgammal",
    "llrintl",
    "llroundl",
    "logl",
    "log10l",
    "log1pl",
    "log2l",
    "logbl",
    "lrintl",
    "lroundl",
    "modfl",
    "nanl",
    "nearbyintl",
    "nextafterl",
    "nexttowardl",
    "powl",
    "remainderl",
    "remquol",
    "rintl",
    "roundl",
    "scalblnl",
    "scalbnl",
    "sinl",
    "sinhl",
    "sqrtl",
    "tanl",
    "tanhl",
    "tgammal",
    "truncl",
    // GNU / C23 extensions
    "exp10",
    "exp10f",
    "sincos",
    "sincosf",
    "lgamma_r",
    "lgammaf_r",
    "lgammal_r",
    "powi",
    "powif",
    // legacy / libm extras
    "finite",
    "finitef",
    "finitel",
    "isnan",
    "isnanf",
    "isnanl",
    "isinf",
    "isinff",
    "isinfl",
    "j0",
    "j1",
    "jn",
    "y0",
    "y1",
    "yn",
};

/// Fixed arity of the FP-argument math.h forms.  Mixed int/FP forms with an
/// integer parameter (other than the FpFirst libm helpers below) are omitted.
/// {IntArgs, FpArgs, FpIsFloat}.
inline constexpr auto kMathArity = std::to_array<LibCArityEntry>({
    {"sqrt", {0, 1}},
    {"sqrtf", {0, 1, true}},
    {"cbrt", {0, 1}},
    {"sin", {0, 1}},
    {"cos", {0, 1}},
    {"tan", {0, 1}},
    {"asin", {0, 1}},
    {"acos", {0, 1}},
    {"atan", {0, 1}},
    {"sinh", {0, 1}},
    {"cosh", {0, 1}},
    {"tanh", {0, 1}},
    {"exp", {0, 1}},
    {"exp2", {0, 1}},
    {"expm1", {0, 1}},
    {"log", {0, 1}},
    {"log2", {0, 1}},
    {"log10", {0, 1}},
    {"log1p", {0, 1}},
    {"fabs", {0, 1}},
    {"fabsf", {0, 1, true}},
    {"floor", {0, 1}},
    {"ceil", {0, 1}},
    {"round", {0, 1}},
    {"trunc", {0, 1}},
    {"rint", {0, 1}},
    {"nearbyint", {0, 1}},
    {"pow", {0, 2}},
    {"powf", {0, 2, true}},
    {"atan2", {0, 2}},
    {"fmod", {0, 2}},
    {"hypot", {0, 2}},
    {"copysign", {0, 2}},
    {"fmax", {0, 2}},
    {"fmin", {0, 2}},
    {"fdim", {0, 2}},
    {"nextafter", {0, 2}},
    {"fma", {0, 3}},
    // FP return with a pointer argument (nan("")) — FpRet, no FP args.
    {"nan", {1, 0, false, false, true}},
    {"nanf", {1, 0, true, false, true}},
    // Mixed int/FP libm: real signature is the FP arg(s) first, then int/ptr,
    // returning FP (FpFirst).  {IntArgs, FpArgs, FpIsFloat, FpFirst}.
    {"ldexp", {1, 1, false, true}},
    {"ldexpf", {1, 1, true, true}},
    {"scalbn", {1, 1, false, true}},
    {"scalbnf", {1, 1, true, true}},
    {"scalbln", {1, 1, false, true}},
    {"scalblnf", {1, 1, true, true}},
    {"frexp", {1, 1, false, true}},
    {"frexpf", {1, 1, true, true}},
    {"modf", {1, 1, false, true}},
    {"modff", {1, 1, true, true}},
});

} // namespace neverd::libc

#endif // NEVERD_LIBC_LIBCMATH_H
