// Development-only conversion of a preserved WHATWG entity table into C++
// literals. Never run by the analyzer, production build or tests. No network.
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/JSON.h"
#include "llvm/Support/SHA256.h"

#include <fstream>
#include <iostream>
#include <map>
#include <stdexcept>
#include <string>

int main(int Argc, char **Argv) {
  try {
    if (Argc != 3)
      throw std::runtime_error("usage: record-entities input.json output.inc");
    std::ifstream Input(Argv[1], std::ios::binary | std::ios::ate);
    if (!Input || Input.tellg() != 145897)
      throw std::runtime_error("unexpected entity snapshot size");
    std::string Bytes(static_cast<size_t>(Input.tellg()), '\0');
    Input.seekg(0);
    Input.read(Bytes.data(), Bytes.size());
    llvm::SHA256 Hash;
    Hash.update(llvm::StringRef(Bytes));
    if (!Input.good() ||
        llvm::toHex(Hash.final(), true) !=
            "d741d877ac77c4194c4ad526b5b4a19aef8dfe411ab840a466891cdbb9f362e6")
      throw std::runtime_error("entity snapshot hash mismatch");
    auto Parsed = llvm::json::parse(Bytes);
    if (!Parsed) {
      llvm::consumeError(Parsed.takeError());
      throw std::runtime_error("invalid entity JSON");
    }
    const auto *Table = Parsed->getAsObject();
    if (!Table || Table->size() != 2231)
      throw std::runtime_error("entity count mismatch");
    std::map<std::string, std::string> Names;
    for (const auto &Pair : *Table) {
      const auto *Entry = Pair.second.getAsObject();
      if (!Entry || !Entry->getString("characters") ||
          !Pair.first.str().starts_with('&') || Pair.first.str().size() > 33)
        throw std::runtime_error("invalid entity entry");
      const auto Name = Pair.first.str().substr(1);
      for (const auto C : Name)
        if (!(C >= 'a' && C <= 'z') && !(C >= 'A' && C <= 'Z') &&
            !(C >= '0' && C <= '9') && C != ';')
          throw std::runtime_error("invalid entity name");
      Names.emplace(Name, Entry->getString("characters")->str());
    }
    std::ofstream Output(Argv[2], std::ios::binary);
    Output
        << "// WHATWG HTML named character reference data.\n"
           "// Copyright WHATWG (Apple, Google, Mozilla, Microsoft).\n"
           "// SPDX-License-Identifier: BSD-3-Clause\n"
           "// See LICENSES/whatwg/ and fixtures/html/README.md.\n"
           "// Generated by fixtures/html/RecordReferences.cpp; do not edit.\n"
           "static constexpr NamedReference NamedReferences[] = {\n";
    constexpr char Hex[] = "0123456789abcdef";
    for (const auto &[Name, Text] : Names) {
      Output << "    {\"" << Name << "\", \"";
      for (const unsigned char C : Text)
        Output << "\\x" << Hex[C >> 4] << Hex[C & 15];
      Output << "\"},\n";
    }
    Output << "};\n";
    if (!Output.good())
      throw std::runtime_error("cannot write entity table");
    std::cout << "recorded " << Names.size() << " named references\n";
    return 0;
  } catch (const std::exception &E) {
    std::cerr << E.what() << '\n';
    return 1;
  }
}
