#!/usr/bin/env python3
"""Extract framework-owned Objective-C declarations from the SDK's libclang.

Only public headers belonging to the requested framework contribute facts.
Imported headers remain separate providers. All four preprocessing profiles
and every signature alternative use the common declaration agreement rules.
"""
import argparse
import ctypes
import json
from pathlib import Path
import re
import tempfile

try:
    from .generate_objc_declarations import Clang, CXCursor, CXString, TARGETS, catalog_rows, framework_module_aliases
except ImportError:
    from generate_objc_declarations import Clang, CXCursor, CXString, TARGETS, catalog_rows, framework_module_aliases

DEFAULT_FRAMEWORKS = (
    "CoreData", "CoreLocation", "CoreSpotlight", "QuartzCore",
    "UniformTypeIdentifiers", "UserNotifications", "WebKit",
)


def framework_header(framework):
    module_paths(framework,
                 f"/System/Library/Frameworks/{framework}.framework/{framework}")
    # QuartzCore.h also imports compatibility headers for CoreImage and
    # CoreVideo. Those declarations belong to separate providers. Its public
    # CoreAnimation umbrella supplies the owned declarations on both targets.
    header = ("CoreAnimation" if framework == "QuartzCore" else
              "WKWebsiteDataStore" if framework == "WebKit" else framework)
    return f"{framework}/{header}.h"


class CXSourceLocation(ctypes.Structure):
    _fields_ = [("data", ctypes.c_void_p * 2), ("integer", ctypes.c_uint)]


def owns_header(path, headers):
    return Path(path).resolve().is_relative_to(headers.resolve())


class FrameworkDeclarations(Clang):
    def __init__(self, library, headers):
        super().__init__(library)
        self.headers = headers
        self.bind("clang_getCursorLocation", CXSourceLocation, CXCursor)
        self.bind("clang_getSpellingLocation", None, CXSourceLocation,
                  ctypes.POINTER(ctypes.c_void_p), ctypes.POINTER(ctypes.c_uint),
                  ctypes.POINTER(ctypes.c_uint), ctypes.POINTER(ctypes.c_uint))
        self.bind("clang_getFileName", CXString, ctypes.c_void_p)

    def declaration(self, cursor):
        if cursor.kind not in (16, 17):
            return None
        file = ctypes.c_void_p()
        self.clang_getSpellingLocation(self.clang_getCursorLocation(cursor),
                                       ctypes.byref(file), None, None, None)
        if not file.value:
            return None
        path = self.string(self.clang_getFileName(file))
        return super().declaration(cursor) if owns_header(path, self.headers) else None


def module_paths(framework, install_name):
    if not re.fullmatch(r"[A-Za-z][A-Za-z0-9]*", framework):
        raise ValueError("invalid framework name")
    root = f"/System/Library/Frameworks/{framework}.framework/"
    if install_name != root + framework and not re.fullmatch(
            re.escape(root) + r"Versions/[A-Za-z0-9]+/" + re.escape(framework), install_name):
        raise ValueError("SDK install name does not identify this public framework")
    return "|".join(sorted(framework_module_aliases(install_name)))


def sdk_module_paths(sdk, framework):
    import yaml

    class TBDLoader(yaml.SafeLoader):
        pass

    TBDLoader.add_constructor(
        "!tapi-tbd", lambda loader, node: loader.construct_mapping(node, deep=True))
    stub = sdk / f"System/Library/Frameworks/{framework}.framework/{framework}.tbd"
    documents = list(yaml.load_all(stub.read_text(), Loader=TBDLoader))
    first = documents[0]
    if first.get("tbd-version") != 4 or not {
            "arm64-macos", "x86_64-macos"}.issubset(first.get("targets", [])):
        raise ValueError("framework export document lacks both architecture profiles")
    return module_paths(framework, first["install-name"])


def render(frameworks, version, compiler):
    lines = ["// clang-format off",
             "// Generated by scripts/generate_objc_framework_declarations.py.",
             f"// Compiler-derived public framework API facts: MacOSX SDK {version}.",
             f"// {compiler}", "// Target profiles: " + ", ".join(TARGETS),
             "// Public imports: " + ", ".join(framework_header(name) for name, _, _ in sorted(frameworks)),
             "// No framework source implementation is included.",
             "// Empty encodings are negative evidence; nullptr means no declaration."]
    for name, modules, profiles in sorted(frameworks):
        for row in catalog_rows(profiles):
            lines.append("{" + ", ".join(
                "nullptr" if value is None else json.dumps(value)
                for value in (name, modules, *row)) + "},")
    return "\n".join(lines + ["    // clang-format on", ""])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sdk", type=Path, required=True)
    parser.add_argument("--libclang", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--framework", action="append")
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    sdk = args.sdk.resolve(strict=True)
    frameworks = []
    for name in sorted(set(args.framework or DEFAULT_FRAMEWORKS)):
        # Validate the name before forming a local SDK path or import.
        module_paths(name, f"/System/Library/Frameworks/{name}.framework/{name}")
        headers = sdk / f"System/Library/Frameworks/{name}.framework/Headers"
        clang = FrameworkDeclarations(args.libclang, headers.resolve(strict=True))
        with tempfile.TemporaryDirectory(prefix="neverd-framework-declarations-") as work:
            source = Path(work) / "declarations.m"
            source.write_text(f"#import <{framework_header(name)}>\n")
            profiles = [clang.extract(source, sdk, target) for target in TARGETS]
        frameworks.append((name, sdk_module_paths(sdk, name), profiles))
    version = json.loads((sdk / "SDKSettings.json").read_text())["Version"]
    output = render(frameworks, version, clang.string(clang.clang_getClangVersion()))
    if args.check:
        if args.output.read_text() != output:
            parser.error("generated catalog differs; regenerate with this SDK")
    else:
        args.output.write_text(output)
    print(f"verified {sum(line.startswith('{') for line in output.splitlines())} framework declarations")


if __name__ == "__main__":
    main()
