#!/usr/bin/env python3
"""Extract compiler-proven Swift SDK metadata call declarations.

Public, nongeneric nominal types come from compiler symbol graphs. Metadata
queries must compile on ARM64/x86-64 macOS and Mac Catalyst; the emitted Swift
calling convention, complete result and request type must agree. SDK exports
authenticate the exact library identities. These profiles are not iOS device
execution evidence. No SDK or Swift implementation is included in the catalog.
"""
import argparse
import json
from pathlib import Path
import re
import subprocess
import tempfile

try:
    from .generate_darwin_declarations import load_exports
except ImportError:
    from generate_darwin_declarations import load_exports


TARGETS = ("arm64-apple-macos15.0", "arm64-apple-ios18.0-macabi",
           "x86_64-apple-macos15.0", "x86_64-apple-ios18.0-macabi")
EXPORT_TARGETS = ("arm64-macos", "arm64-maccatalyst",
                  "x86_64-macos", "x86_64-maccatalyst")
MODULES = ("Foundation", "_Concurrency")


def nominal_types(document, module="Foundation"):
    if document.get("module", {}).get("name") != module:
        raise ValueError(f"symbol graph does not identify {module}")
    symbols = document.get("symbols")
    if not isinstance(symbols, list) or len(symbols) > 200000:
        raise ValueError("invalid symbol graph inventory")
    result = {}
    for symbol in symbols:
        if symbol.get("kind", {}).get("identifier") not in {
                "swift.struct", "swift.enum", "swift.class"}:
            continue
        identity = symbol.get("identifier", {})
        path = symbol.get("pathComponents", [])
        if (identity.get("interfaceLanguage") != "swift" or
                not identity.get("precise", "").startswith("s:") or
                symbol.get("accessLevel") not in {"public", "open"} or
                len(path) != 1 or not re.fullmatch(r"[A-Za-z_][A-Za-z_0-9]*", path[0]) or
                symbol.get("swiftGenerics", {}).get("parameters")):
            continue
        name, precise = path[0], identity["precise"]
        if name in result and result[name] != precise:
            raise ValueError("ambiguous public nominal declaration")
        result[name] = precise
    return result


def common_nominals(profiles):
    if len(profiles) != len(TARGETS):
        raise ValueError("all four symbol graph profiles are required")
    names = set.intersection(*(set(profile) for profile in profiles))
    return sorted(name for name in names
                  if len({profile[name] for profile in profiles}) == 1)


def metadata_calls(ir, nominal_identities):
    if len(ir) > 16 * 1024 * 1024:
        raise ValueError("metadata query IR exceeds the input budget")
    if not re.search(r"^%swift\.metadata_response = type \{ ptr, i64 \}$", ir, re.M):
        return set()
    # Only declarations actually used by a compiled .self query contribute.
    # Generic accessors or incidental runtime declarations with additional
    # parameters cannot acquire the one-request ABI by a symbol suffix.
    declarations = set(re.findall(
        r'^declare swiftcc %swift\.metadata_response @"([^"\n]+)"\(i64\)(?: [^\n]*)?$',
        ir, re.M))
    calls = set(re.findall(
        r'\bcall swiftcc %swift\.metadata_response @"([^"\n]+)"\(i64 0\)', ir))
    # A precise public nominal identity supplies the accessor role. The suffix
    # alone supplies no ABI: the compiler's declaration and actual query above
    # must independently agree. This excludes incidental runtime calls.
    accessors = {"$s" + identity[2:] + "Ma" for identity in nominal_identities
                 if re.fullmatch(r"s:[A-Za-z_0-9$]+", identity)}
    return declarations & calls & accessors


def render(profiles, exports, version, compiler):
    if len(profiles) != len(TARGETS) or len(exports) != len(TARGETS):
        raise ValueError("all four ABI and export profiles are required")
    lines = ["// clang-format off",
             "// Generated by scripts/generate_swift_metadata_declarations.py.",
             f"// Compiler-derived metadata call facts: MacOSX SDK {version}.",
             "// " + compiler.replace("\n", "; "),
             "// Target profiles: " + ", ".join(TARGETS),
             "// swiftcc {ptr, i64}(i64), without hidden or generic arguments.",
             "// Public nominal queries and exact SDK exports; no implementation included."]
    for name in sorted(set.intersection(*profiles)):
        modules = [sorted(exports[i].get(name, set()) &
                          exports[i + 1].get(name, set())) for i in (0, 2)]
        if not all(modules):
            continue
        lines.append("{" + ", ".join(json.dumps(value) for value in
                                     (name, *("|".join(m) for m in modules))) + "},")
    return "\n".join(lines + ["// clang-format on", ""])


def run(command):
    return subprocess.run(command, check=True, capture_output=True, text=True,
                          timeout=180).stdout


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sdk", type=Path, required=True)
    parser.add_argument("--swiftc", type=Path, required=True)
    parser.add_argument("--symbolgraph-extract", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    sdk = args.sdk.resolve(strict=True)
    with tempfile.TemporaryDirectory(prefix="neverd-swift-metadata-") as work:
        directory = Path(work)
        graphs = []
        for index, target in enumerate(TARGETS):
            output = directory / str(index)
            output.mkdir()
            profile = {}
            for module in MODULES:
                module_output = output / module
                module_output.mkdir()
                run([str(args.symbolgraph_extract), "-module-name", module,
                     "-target", target, "-sdk", str(sdk),
                     "-minimum-access-level", "public", "-skip-inherited-docs",
                     "-skip-synthesized-members", "-skip-protocol-implementations",
                     "-output-dir", str(module_output)])
                declarations = nominal_types(json.loads(
                    (module_output / f"{module}.symbols.json").read_text()), module)
                profile.update({(module, name): identity
                                for name, identity in declarations.items()})
            graphs.append(profile)
        names = common_nominals(graphs)
        if not names:
            parser.error("no common public nominal declarations")
        source = directory / "queries.swift"
        source.write_text(
            "\n".join(f"import {module}" for module in MODULES) + "\n" +
            "\n".join(
                f'@_cdecl("metadata_probe_{i}")\n'
                f'public func metadataProbe{i}() -> UnsafeRawPointer {{ '
                f'unsafeBitCast({module}.{name}.self, '
                f'to: UnsafeRawPointer.self) }}'
                for i, (module, name) in enumerate(names)) + "\n")
        profiles = []
        for index, target in enumerate(TARGETS):
            ir = directory / f"{index}.ll"
            run([str(args.swiftc), "-O", "-parse-as-library", "-module-name", "MetadataProbe",
                 "-target", target, "-sdk", str(sdk), "-emit-ir", str(source), "-o", str(ir)])
            profiles.append(metadata_calls(ir.read_text(),
                                           (graphs[index][name] for name in names)))
    output = render(profiles, load_exports(
        sdk, targets=EXPORT_TARGETS,
        extra_libraries=("libswift_Concurrency",)),
                    json.loads((sdk / "SDKSettings.json").read_text())["Version"],
                    run([str(args.swiftc), "--version"]).strip())
    count = sum(line.startswith("{") for line in output.splitlines())
    if not count:
        parser.error("no metadata calls have complete declaration and export evidence")
    if args.check:
        if args.output.read_text() != output:
            parser.error("generated metadata catalog differs")
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile(mode="w", dir=args.output.parent,
                                         delete=False) as temporary:
            temporary.write(output)
            staging = Path(temporary.name)
        try:
            staging.replace(args.output)
        finally:
            staging.unlink(missing_ok=True)
    print(f"verified {count} metadata call declarations from {len(names)} public nominals")


if __name__ == "__main__":
    main()
